### ISSUE TITLE
Le rang centile dans signets est de 65, cependant c'est 62 dans l'application. il en va de même pour mon autre cours.

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#10]
**What happened:**
```
Le rang centile dans signets est de 65, cependant c'est 62 dans l'application. il en va de même pour mon autre cours.
```

**Version:** 3.0.0-beta (31254)

**Operating system:** Android 9

**Model:** samsung SM-G950W

**Memory:** 62% (2.04 GB used out of 3.27 GB)

**Capacity:** 37% (19.5 GB used out of 53.3 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/43/awesome_logs) 

**Attachments:** 

![screenshot_1597603811811.png](http://buglife.s3.amazonaws.com/report_attachments/f0cf92d9a8734976dc5a9595a81f55c6d6732444/original/screenshot_1597603811811.png?1597603991)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/43

Reported via Buglife

**Comment by apomalyn** [comment]
Mauvais repo
