### ISSUE TITLE
Return to current week bug

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#1000]
**Describe the issue** 
```Affiche "Deja sur l'horaire d'aujourd'hui" même si je change de semaine```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-292570884.png?raw=true)

**Device Infos** 
- **Device:** moto g pure 
- **Version:** 4.21.5 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1679695472 
- **Platform operating system:** android 
- **Platform operating system version:** RRH31.Q3-46-50-2 
- **Email:** null

**Comment by LouisPhilippeHeon** [comment]
C'est le comportement voulu non? On peut voir que effectivement il a changé de semaine dans le menu en haut de l'écran mais il a pas sélectionné une journée de celle-ci, donc techniquement il est déjà aujourd'hui. Cela dit on pourrait quand même faire en sorte que ça s'applique pour le menu au haut de l'écran.

**Comment by XavierPaquet-Rapold** [comment]
@LouisPhilippeHeon le comportement attendu serait que l'horaire revienne à la semaine actuelle même si aucun jour est sélectionné dans l'autre semaine
