### ISSUE TITLE
The text in the ÉTS page doesn't handle well long titles

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#101]
**Describe the bug**
"L'heuristique" does not fit on one line when the phone is smaller.

**To Reproduce**
1. Go to 'ÉTS'

**Expected behavior**
The card should be bigger, or the text should be smaller to fit the card, or maybe add an overflow property on the text.

**Screenshots**
<img height="380" alt="Capture d’écran, le 2021-04-22 à 21 43 05" src="https://user-images.githubusercontent.com/37625944/115805822-b967e780-a3b3-11eb-9c8f-824105fc860d.png">

**Comment by AlexandreMarkus** [comment]
also, the look is weird. I would space the cards evenly with a bigger space between them

**Comment by camillebrulotte** [comment]
Forgot to close it
