### ISSUE TITLE
Code cours déborde

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#1027]
**Describe the issue** 
```Le code de cours ne rentre pas dans la largeur des blocs de cours ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-422802602.png?raw=true)

**Device Infos** 
- **Device:** Pixel 6 
- **Version:** 4.50.1 
- **Connectivity:** [ConnectivityResult.wifi] 
- **Build number:** 1721687577 
- **Platform operating system:** android 
- **Platform operating system version:** AP2A.240705.004 
- **Email:** jaisal.patel.1@ens.etsmtl.ca

**Comment by LouisPhilippeHeon** [comment]
On pourrait masquer le samedi si il n'y a aucun cours cette journée-là, ce qui laisserait plus de place pour les autres jours. Malheureusement je pense que on n'a pas le choix d'avoir du overflow dans certains cas, réduire la taille de la police n'est pas une bonne idée en terme d’accessibilité.
