### ISSUE TITLE
je ne suis pas capable d'accéder à mon ets à partir de l'appli

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#126]
**What happened:**
```
je ne suis pas capable d'accéder à mon ets à partir de l'appli
```

**Version:** 3.0.0-beta (30885)

**Operating system:** Android 9

**Model:** samsung SM-G973W

**Memory:** 50% (3.68 GB used out of 7.3 GB)

**Capacity:** 14% (15 GB used out of 109 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Disconnected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/17/awesome_logs) 

**Attachments:** 

![screenshot_1557246558036.png](http://buglife.s3.amazonaws.com/report_attachments/985b3867628abfe1b5ae491af39fe92e9f33f033/original/screenshot_1557246558036.png?1557246716)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/17

Reported via Buglife

**Comment by Sonphil** [comment]
MonÉTS semble être accessible à partir de l'application.
