### ISSUE TITLE
Onboarding screen rendering issues

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#129]
**Describe the bug**
When a user opens up the app for the first time, the onboarding screen seems to have cutting issues. I'm assuming that the screen is complete and doesn't have any cuts. Since I see the wave pattern emerging, I thought that it might also be voluntary, but cannot be seen as easily with the dark theme.

**To Reproduce**
1. Open the app for the first time (I suppose clearing the app's data can make the onboarding appear again)

**Expected behavior**
I thought the onboarding screen should be at least full, but the wave effect might be wished, although only clearly visible on the light theme.

**Screenshots**
![Screenshot_20210525-204252](https://user-images.githubusercontent.com/1891861/120075362-f0927e00-c06e-11eb-8966-03b583a8c6a6.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Browser: Chrome Beta
 - Version: 91

**Additional context**
I just wanted to tell you guys nice job with this release. It really looks great and I can't wait to see the finished product! 🙂 I also have a bunch of issues so stay tuned.

**Comment by camillebrulotte** [comment]
Good point ! Technically, it's just that the card behind is the same color as the "discovery bubble". But I agree that it can be confusing when looking at it ! :D 

I think we could change the color of the "discovery bubble" to make it darker or lighter so it adds contrast! 
What do you think ? @apomalyn  @AlexandreMarkus 

Thank you for the report :)

**Comment by apomalyn** [comment]
@camillebrulotte I agree with you! 😃
