### ISSUE TITLE
Lack of haptic feedback when long-pressing on a dashboard card

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#139]
**Describe the bug**
The user should be able to feel when a card has been long pressed in the dashboard, but instead we only see the shadow indicating it can be moved. The shadow itself is harder to see when the dark theme is used in the app.

**To Reproduce**
1. Go to the Dashboard
2. Long press on any card

**Expected behavior**
That a haptic feedback is present alongside the shadow when long-pressing on a card

**Screenshots**
None

**Smartphone (please complete the following information):**
- Device: Pixel 3a
- OS: Android 11
- Browser: Chrome Beta
- Version: 91

**Additional context**
None

**Comment by AlexandreMarkus** [comment]
That haptic feedback could be enabled or not in the more: settings section(user preferences). What do you think about it?

**Comment by zaclimon** [comment]
Not sure how it goes in iOS, but in Android, most if not all long-press gestures have haptic feedback in them and as defined in the [guidelines](https://material.io/design/platform-guidance/android-haptics.html#usage). You can try in any app or even in your launcher if you want to confirm.

Also I believe that the choice of using haptic feedback should be left to the device's settings and that the app shouldn't have to override what has been defined in the system. How do you see this?

**Comment by apomalyn** [comment]
@zaclimon I do agree with you about the haptic feedback, personally I disabled it ahah. 
@AlexandreMarkus we could use [Feedback](https://api.flutter.dev/flutter/material/Feedback-class.html) which should be disabled if the touch feedback is disable on the device (to test :sweat_smile:)what do you think about this?

**Comment by AlexandreMarkus** [comment]
> @zaclimon I do agree with you about the haptic feedback, personally I disabled it ahah. 
> @AlexandreMarkus we could use [Feedback](https://api.flutter.dev/flutter/material/Feedback-class.html) which should be disabled if the touch feedback is disable on the device (to test :sweat_smile:)what do you think about this?
> 
> 

Excellent
