### ISSUE TITLE
Lack of transitions between the app sections

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#141]
**Describe the bug**
Call me picky, but I like smooth transitions and animations and not seeing them makes me sad a little more every day. 😢  But yeah it's kinda self-explanatory.

**To Reproduce**
1. Move around in the application

**Expected behavior**
Having smooth transitions as smooth as those demos you see Google doing. 🧈 

**Screenshots**
Comparison between ÉTSMobile V3 and V4:

https://user-images.githubusercontent.com/1891861/120710935-c38a0500-c48c-11eb-8fc8-75ad8b264294.mp4

**Smartphone (please complete the following information):**
- Device: Pixel 3a
- OS: Android 11
- Browser: Chrome Beta
- Version: 91

**Additional context**

**Comment by apomalyn** [comment]
This one is going to be tricky, if we want to have animation between the pages (like the one between Grades and Profile) we will have to completely change the architecture of how we navigate into the application. We can try to use a route transition 🤔 

For the grades pages, this one need to be added, I do agree.

**Comment by AlexandreMarkus** [comment]
> This one is going to be tricky, if we want to have animation between the pages (like the one between Grades and Profile) we will have to completely change the architecture of how we navigate into the application. We can try to use a route transition 🤔 
> 
> For the grades pages, this one needs to be added, I do agree.

I think the easiest way would be to add material design pages transition, but if you remember the app is less snappier with that.
