### ISSUE TITLE
About ETSMobile animation too slow?

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#142]
**Describe the bug**
I find it too slow to my liking (~3-4s), but that might be a design decision.

**To Reproduce**
1. Go to "More"
2. Select "About App|ETS"

**Expected behavior**
Be ~1-2s

**Screenshots**
Comparison between ETSMobile V3 and V4:

https://user-images.githubusercontent.com/1891861/120712769-106edb00-c48f-11eb-82ec-9b040bff2c5d.mp4

**Smartphone (please complete the following information):**
- Device: Pixel 3a
- OS: Android 11
- Browser: Chrome Beta
- Version: 91

**Additional context**
None

**Comment by AlexandreMarkus** [comment]
We had a discussion about the time of duration for the animation. Since it is a page that won't be open often, the duration can be slower than in v3. We want to make the animation smooth and nice. Personally I find the animation in v3 a bit fast.

**Comment by zaclimon** [comment]
Sounds reasonable, then in that case how about adjusting the easing? I think that the animation takes more time to reach the bottom than when it originally started.

**Comment by MysticFragilist** [comment]
Hi @zaclimon, sorry for the delay! But by adjusting the easing what do you mean? By looking a bit at the code, I think it's actually an optical illusion that it seems to go faster. The animation doesn't use any special easing option, it's a straight-up linear animation. But, maybe putting a real ease-out, could make it look like it's more "on purpose" and make it look less "bugged", I don't know. Personally, I find the easing animation in v4 good, but if everyone can agree to change it, I could make a quick PR to modify it! :)

**Comment by AlexandreMarkus** [comment]
> Hi @zaclimon, sorry for the delay! But by adjusting the easing what do you mean? By looking a bit at the code, I think it's actually an optical illusion that it seems to go faster. The animation doesn't use any special easing option, it's a straight-up linear animation. But, maybe putting a real ease-out, could make it look like it's more "on purpose" and make it look less "bugged", I don't know. Personally, I find the easing animation in v4 good, but if everyone can agree to change it, I could make a quick PR to modify it! :)

I think we can close this issue. It's normal that the blue color takes more time to reach the bottom versus the top, since it doesn't have the same distance to travel. The blue color is actually a blue circle growing.

**Comment by zaclimon** [comment]
> Hi @zaclimon, sorry for the delay! But by adjusting the easing what do you mean? By looking a bit at the code, I think it's actually an optical illusion that it seems to go faster. The animation doesn't use any special easing option, it's a straight-up linear animation. But, maybe putting a real ease-out, could make it look like it's more "on purpose" and make it look less "bugged", I don't know. Personally, I find the easing animation in v4 good, but if everyone can agree to change it, I could make a quick PR to modify it! :)

No worries! At this stage it's a personal preference since I prefer snappier animations. Perhaps as @AlexandreMarkus said, I'm seeing it as a slower animation because its duration is longer than what was specified in V3.

In that case, I'll close the issue.  Keep it up! 👍🏾
