### ISSUE TITLE
Open-Source: Spacing too narrow between title and logo

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#143]
**Describe the bug**
Similar to #132, the spacing is a little bit too narrow. Not sure if it's the way it's being handled or perhaps the library that is used if any.

**To Reproduce**
1. Go to "More"
2. Select "Open-source licenses"
3. Select "Show licenses"

**Expected behavior**
More vertical spacing between the logo and the title

**Screenshots**
![Screenshot (3 juin 2021 17 h 21 min 42 s)](https://user-images.githubusercontent.com/1891861/120713711-482a5280-c490-11eb-87c0-a2580a838f18.png)

**Smartphone (please complete the following information):**
- Device: Pixel 3a
- OS: Android 11
- Browser: Chrome Beta
- Version: 91

**Additional context**
None

**Comment by AlexandreMarkus** [comment]
@zaclimon you are on 🔥man! Good catch here! I will take a look at what I can do about it since it is an automatically generated widget. I will try to add some spacing if I can.

**Comment by zaclimon** [comment]
@AlexandreMarkus You guys are the ones killing it at the moment haha. I'm just adding some QA so everything looks shiny. 😉
