### ISSUE TITLE
Add home widgets

### ISSUE THREAD

**Issue by elornHamon** [ApplETS/Notre-Dame#145]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to see the schedule on my home screen

**Describe the solution you'd like**
Adding a home screen widget that displays the schedule.

**Additional context**
Flutter home widget example repo: https://github.com/hemanthrajv/flutter_home_screen_widget_example

**Acceptation criteria**

- [ ] Documentation
- [x] Test
- [x] User can add a home screen widget that displays the schedule for the day
- [x] User can add a home screen widget that displays the progress bar of the session
- [ ] User can add a home screen widget that displays the courses of the session

**Comment by AlexandreMarkus** [comment]
https://pub.dev/packages/home_widget

**Comment by MysticFragilist** [comment]
Great idea! would they all fit tho? I don't know if it's possible, I don't really use home screen widget honestly hahaha 😄

**Comment by apomalyn** [comment]
> Great idea! would they all fit tho? I don't know if it's possible, I don't really use home screen widget honestly hahaha smile

I though of each card could be a widget :smile:

**Comment by eneiss** [comment]
A nice tutorial I found for the iOS part: https://itnext.io/develop-an-ios-14-widget-in-flutter-with-swiftui-e98eaff2c606

**Comment by MysticFragilist** [comment]
We could check that to be able to debug widget, with a bit of dark magic, it will work with those env variable :smile: :
https://developer.apple.com/documentation/widgetkit/debugging-widgets

This article will maybe help to understand what we can do to refresh a widget:
https://developer.apple.com/documentation/widgetkit/keeping-a-widget-up-to-date
Unfortunately it doesn't seem like we can do what we are doing (reloading from a background worker) at the moment.

The other thing we could do as last resort, would be to use the widgetkit_flutter package (it has a reloadTimeline() func in dart):
https://itnext.io/develop-an-ios-14-widget-in-flutter-with-swiftui-e98eaff2c606
We would have to do a check to only use it when on an iOS platform. It would be easier to do, but maybe feel a little bit hacky as we would have two differents packages to distribute the information (One for iOS and one for Android).

Also, we could follow this small tutorial at the end of the development ^^:
https://developer.apple.com/documentation/widgetkit/widget-suggestions-in-smart-stacks

**Comment by eneiss** [comment]
Here are the 2 (WIP) widgets I'm working on: session progress and grades.
There are many things that could (and ideally will) be improved in the UI, but if you already have feedback on the general layout, ideas on how to do it better or anything else, I'll gladly hear it 😊 

I also regularly update [the corresponding project](https://github.com/ApplETS/Notre-Dame/projects/15) with my current progress, don't hesitate to leave some feedback on it too if I forgot something for example.

![widgets_white](https://user-images.githubusercontent.com/33004979/153095544-00897500-cfd3-4771-8675-2455a54098f1.png)
![widgets_dark](https://user-images.githubusercontent.com/33004979/153095557-bdfb6a07-dfbe-4003-a895-fe4019a73609.png)

**Comment by AlexandreMarkus** [comment]
Very nice! I think it would be useful to also have a third widget with today's schedule ;)

**Comment by eneiss** [comment]
> Very nice! I think it would be useful to also have a third widget with today's schedule ;)

It comes next! It just seemed to be the hardest to make at first, but it should be ok 😄

**Comment by eneiss** [comment]
@MysticFragilist and I worked together on the iOS widgets this afternoon, both session progress and grades widgets should now be working correctly and are available in English and French! 🥳 

We changed the UI for the progress widget a bit, the displayed format should be configurable in a future PR, for now we just went with the current / total days.

Here's how they look now!
<img src="https://user-images.githubusercontent.com/33004979/154821782-c8015051-3e9e-4fe5-b835-db56d5b6ea9e.png" width="300"> <img src="https://user-images.githubusercontent.com/33004979/154821788-ac8636d7-8959-4838-965b-c11d34cc8a32.png" width="300"> <img src="https://user-images.githubusercontent.com/33004979/154821785-0ea39f5c-8808-4915-b8d6-2bb531b6196b.png" width="300">

The corresponding PR will follow soon, we just need to add some tests to the Flutter side 😄

**Comment by camillebrulotte** [comment]
Ouhh trop nice bien joué ! 🥳🥳

Je lance çaa mais pour la progress bar peut-être que faire une progress bar rond ça aiderait à rendre ça moins comme "rectangulaire"/"lister" ? Je sais pas à quel point c'est faisable par contre ..... hahaa

Aussiii peut-être mettre le même gris qu'on a en dark theme dans l'app pour pas faire trop trop sombre ? 😊 
Puis le padding entre la ligne et le texte dans celle de Notes où on pourrait mettre le même en haut et en bas pour pas quelle soit trop collé au texte ? 

Vous en pensez quoi 😊 

J'ai fait quick quick une idée ! 

<img width="762" alt="Capture d’écran, le 2022-02-20 à 11 31 41" src="https://user-images.githubusercontent.com/37625944/154853220-62d0add6-8754-43b1-a170-e23697da0a7a.png">

**Comment by eneiss** [comment]
Je suis entièrement d'accord avec tous les points 😄 
Le design c'est pas mon point fort haha, merci beaucoup pour tout ce feedback !

La progress bar ronde avait l'air un peu compliquée à faire mais en fait ça devrait aller, je viens de trouver un tuto qui en fait une de manière assez simple ([lien ici](https://www.simpleswiftguide.com/how-to-build-a-circular-progress-bar-in-swiftui/)), je vais tenter ça bientôt !
Et ok pour le reste, je vais essayer de suivre tes idées, je suis pas encore très à l'aise avec SwiftUI mais je vais faire ce que je peux !

**Comment by camillebrulotte** [comment]
Ah ben non c'était super bien partie ! :D Ahh nice ça serait perf !!

**Comment by eneiss** [comment]
J'ai update le widget de progression pour correspondre à peu près à l'idée de @camillebrulotte, je vous laisse voir ce que ça donne et me dire ce que vous en pensez 😊 
(J'ai aussi changé la couleur de fond en mode sombre pour les deux widgets)

J'aurais quelques questions de choix de design, si vous avez des avis dessus hésitez pas à les donner ici !

Entre autres : 
 - Est-ce que vous préférez la version avec ou sans la barre complète derrière la barre de progression ?
 - Quelle couleur de fond vous préférez pour le dark theme (cf le screen où je les ai numérotées) ? 
 La couleur 1 correspondant à `darkThemeBackground / #303030` et la 2 à `etsBlack / #2E2A25`
 - Est-ce que vous pensez que c'est mieux d'avoir l'affichage en % et en ratio de jours en même temps ou on en laisse qu'un des deux à la fois et on rend le widget configurable ?
 
Si vous avez d'autres remarques sur ce widget, je suis preneuse aussi 😁 

<img width="209" alt="Screen Shot 2022-02-22 at 4 46 53 PM" src="https://user-images.githubusercontent.com/33004979/155226631-cf00bbda-55ca-4183-94c9-d6efcee9419e.png"> <img width="217" alt="Screen Shot 2022-02-22 at 4 46 06 PM" src="https://user-images.githubusercontent.com/33004979/155226642-3ddffbef-8553-4507-bc46-2a162fbc6432.png">

<img width="400" alt="Comparaison couleurs" src="https://user-images.githubusercontent.com/33004979/155226696-0ae41f99-e37c-4b91-91e4-146061d2c69e.jpeg">
