### ISSUE TITLE
La moyenne de la classe est mauvaise, sue signets la moyenne est 5/7. C'est bizzare une moyenne plus grande que 100% dans ce cas-ci. 

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#145]
**What happened:**
```
La moyenne de la classe est mauvaise, sue signets la moyenne est 5/7. C'est bizzare une moyenne plus grande que 100% dans ce cas-ci. 
```

**Version:** 3.0.0-beta (30952)

**Operating system:** Android 9

**Model:** ONEPLUS A5010

**Memory:** 80% (6.04 GB used out of 7.54 GB)

**Capacity:** 45% (50.2 GB used out of 111 GB)

**Locale:** United States English

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/18/awesome_logs) 

**Attachments:** 

![screenshot_1558975064251.png](http://buglife.s3.amazonaws.com/report_attachments/9b77ec75f9ce7e9d967a50b702865494f34fb5e3/original/screenshot_1558975064251.png?1558975342)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/18

Reported via Buglife

**Comment by Sonphil** [comment]
The user confirmed that #148 fixed the issue.

> Bonjour, 
en effet je n'étais pas présent lors du Mtest1 alors il a entré la note de 0. L'application semble voir comme si la note n'existait pas encore. 
Je confirme que la mise à jour que tu viens de faire régle le problème. 
Merci 
G******
