### ISSUE TITLE
Wrong message displayed when using the app in offline mode

### ISSUE THREAD

**Issue by JonathanDuvalV** [ApplETS/Notre-Dame#151]
**Describe the bug**
When using the app in offline mode with data from the cache when the user was previously logged in, most pages display "No internet connection" except for grades details and dashboard. 

**To Reproduce**
1. Log in to the app
2. Navigate to every page to fill the cache
3. Exit the app entirely ( Do not logout )
4. Turn off wifi and cellular data
5. Open the app (log in should be skipped)
6. Navigate to dashboard
7. Dashboard will display "An error occured"
8. Navigate to grade details
9. Grades details will display "An error occured"

**Expected behavior**
Display "No internet connection" instead of "An error occured" when using the  app in offline mode for the Dashboard and Grades details.

**Screenshots**
Dashboard:
![image](https://user-images.githubusercontent.com/45638733/121762305-04c08b80-cb03-11eb-92cb-673da52e316c.png)

Grade details:
![image](https://user-images.githubusercontent.com/45638733/121762315-130ea780-cb03-11eb-9703-2d134aba8084.png)

Schedule ( what should appear in the other pages ):
![image](https://user-images.githubusercontent.com/45638733/121762332-3174a300-cb03-11eb-8501-e86e5f6860be.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.6

**Comment by zaclimon** [comment]
This might be a stretch to pull on, but I have a suggestion. How about instead of spamming a Toast of "No internet connection", we only show once that the app is running into "offline" mode? It could be shown inside the dashboard. Below is an example with YouTube on Android.

![Screenshot_20210613-154653](https://user-images.githubusercontent.com/1891861/121820094-d6f05980-cc5e-11eb-8476-814178750eff.png)

**Comment by AlexandreMarkus** [comment]
> This might be a stretch to pull on, but I have a suggestion. How about instead of spamming a Toast of "No internet connection", we only show once that the app is running into "offline" mode? It could be shown inside the dashboard. Below is an example with YouTube on Android.
> 
> ![Screenshot_20210613-154653](https://user-images.githubusercontent.com/1891861/121820094-d6f05980-cc5e-11eb-8476-814178750eff.png)

I like this idea, we could use a [snackbar](https://api.flutter.dev/flutter/material/SnackBar-class.html) right above the bottomNavigationBar and leave it on until the internet is back on. In that case, we should add an "action" button to dismiss the snackbar

**Comment by JonathanDuvalV** [comment]
> This might be a stretch to pull on, but I have a suggestion. How about instead of spamming a Toast of "No internet connection", we only show once that the app is running into "offline" mode? It could be shown inside the dashboard. Below is an example with YouTube on Android.
> 
> ![Screenshot_20210613-154653](https://user-images.githubusercontent.com/1891861/121820094-d6f05980-cc5e-11eb-8476-814178750eff.png)

Good idea ill work on that!
