### ISSUE TITLE
Grade details: colour doesn't change depending on the grade

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#152]
**Describe the bug**
As a student, I would like to have visual feedback on how I perform in an evaluation.

**Expected behaviour**
Here is a screenshot of v3.beta which introduced the colour system:

<details>
  <summary>v3 beta</summary>
  
<img src="https://user-images.githubusercontent.com/22211097/122224368-0a5efe00-ce82-11eb-889b-1f0dbba9cca4.png" data-canonical-src="https://user-images.githubusercontent.com/22211097/122224368-0a5efe00-ce82-11eb-889b-1f0dbba9cca4.png" height="500" />
  
</details>

**Screenshots**
<details>
  <summary>Here is the current version of the application</summary>
  
<img src="https://user-images.githubusercontent.com/22211097/122154159-584c1580-ce32-11eb-8850-8a5f852d4bf4.png" data-canonical-src="https://user-images.githubusercontent.com/22211097/122154159-584c1580-ce32-11eb-8850-8a5f852d4bf4.png" height="500" />  
</details>

As you can see, all the outside circles are green but they should have different colour based on the group or the exact note.
[Go here](https://github.com/ApplETS/Notre-Dame-v3/blob/c4c5c86a54fe16e19a5f7eeea3a0dfb7076207ad/android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/gradesdetails/ArgbEvaluatorExt.kt) to check the beta implementation.

**Comment by camillebrulotte** [comment]
Ahh oui je comprends ce que tu veux dire ! Mais je crois que tu as mis deux fois le même screenshot, ça se peut ? @apomalyn

**Comment by apomalyn** [comment]
@camillebrulotte exact c'etait le meme screenshots XD ca devrait etre regle maintenant :smile:
