### ISSUE TITLE
Unexpected logoff at random

### ISSUE THREAD

**Issue by JonathanDuvalV** [ApplETS/Notre-Dame#156]
**Describe the bug**
Login seems to expire at random once every 1 or 2 weeks

**To Reproduce**
Unknown steps, behavior seems to happen at random

**Expected behavior**
Not getting logged off and keep your cache

**Screenshots**
<details open>
<summary>Video of the issue</summary>
<br>

https://user-images.githubusercontent.com/45638733/122647867-5913ce80-d0f4-11eb-9804-60e5429d6dc8.mp4

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.5

**Comment by elornHamon** [comment]
Also happening on my device, I can't tell if it's totally random or some kind of credential expiring behaviour as it seems to happen when I haven't logged onto the app in a while.

**Smartphone :**
- Device: Pixel 2 XL
- OS: Android 11 (May 1st, 2021 system update)

**Comment by JonathanDuvalV** [comment]
@MysticFragilist It hasn't happened on my phone either for a while now! I would give it one more week, if it still doesn't happen, we could close the issue.

**Comment by apomalyn** [comment]
Not happening anymore! 🚀
