### ISSUE TITLE
Adapt overscroll behavior

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame#160]
**Describe the bug**
ETS's colors are red and white, however the overscroll color is green on my device. Also shouldn't the app not overscroll when there are not enough elements on a list?

**To Reproduce**
1. Go to any screen
2. Overscroll (scrolling on a list that has already reached its end)

**Expected behavior**
Having a color that represent the overscroll behavior well (probably red in that case) and ensure that the app doesn't overscroll everywhere

**Screenshots**

https://user-images.githubusercontent.com/1891861/123529750-7bdc4f00-d6c1-11eb-8112-1f3867dd8672.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Browser Chrome Beta 
 - Version 92

**Additional context**
None

**Comment by apomalyn** [comment]
Well, the application should overscroll everywhere because every screen is a list :sweat_smile: 

Otherwise I do agree the overscroll should be in red.

**Comment by zaclimon** [comment]
Yeah I see what you mean! I might be wrong, but if a list doesn't have enough elements to be scrolled, then I would have thought that it shouldn't overscroll by default.

However, when I see other apps like Settings, the same behavior applies so I guess it's not a big issue.

**Comment by AlexandreMarkus** [comment]
Yes we should change the overscroll color to red. I did pass some time with @apomalyn to find how to change the color via the theme. For more context, the color was red before flutter 2.2 but blue after that.
