### ISSUE TITLE
bug1:
je n arrive pas à mettre un screenshot de mon problème, il n y a pas moyen d importer d image.

bug2:
lorsqu il y a juste 1 note entrée dans un cours, la moyenne de la classe n est pas rapportee sur 100%:
18.7/100 (18.7%)

ça devrais être:
18.7/100 (74.8%)




### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#160]
**What happened:**
```
bug1:
je n arrive pas à mettre un screenshot de mon problème, il n y a pas moyen d importer d image.

bug2:
lorsqu il y a juste 1 note entrée dans un cours, la moyenne de la classe n est pas rapportee sur 100%:
18.7/100 (18.7%)

ça devrais être:
18.7/100 (74.8%)



```

**Version:** 3.0.0-beta (30964)

**Operating system:** Android 9

**Model:** samsung SM-A530W

**Memory:** 73% (2.66 GB used out of 3.61 GB)

**Capacity:** 68% (16.5 GB used out of 24.2 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/23/awesome_logs) 

**Attachments:** 

![screenshot_1561467786854.png](http://buglife.s3.amazonaws.com/report_attachments/5f7ec03e91b96ab0f44378adb4e85bfdc84e6e4c/original/screenshot_1561467786854.png?1561468160)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/23

Reported via Buglife

**Comment by Sonphil** [comment]
Puisque le problème a été corrigé dans une version ultérieure, j'ai invité l'utilisateur à mettre à jour l'application sur son appareil.
