### ISSUE TITLE
Affichage incomplet des notes dashboard pour un 6e cours

### ISSUE THREAD

**Issue by buzzben** [ApplETS/Notre-Dame#164]
Tout est dans le titre: 
![Screenshot_20190703-104238_TSMobile bta](https://user-images.githubusercontent.com/5466030/60601851-c94aad80-9d80-11e9-83da-460ee9fc767f.jpg)

**Comment by Sonphil** [comment]
Salut @buzzben,

J'ai effectué des changements qui devraient permettre de régler ce problème. Merci de l'avoir rapporté!

**Comment by buzzben** [comment]
> Salut @Sonphil 
Thanks :) je crois que je vais partir un autre tread aussi pour le boutton "report a bug" qui semblait ne pas fonctionner, mais je dois revalider.
