### ISSUE TITLE
Remove heuristique from quicklinks

### ISSUE THREAD

**Issue by AlexandreMarkus** [ApplETS/Notre-Dame#164]
**Describe the bug**
Since heuristique is not maintained anymore, I would like to remove the heuristique quicklink.
http://lheuristique.ca/article.php?id=534

I would also like to add analytics on clicks.

**Expected behavior**
I would like to keep the chrome custom tabs opening. On iOS it is called SFSafariViewController.
https://developer.chrome.com/docs/android/custom-tabs/overview/

**Comment by camillebrulotte** [comment]
@AlexandreMarkus On peut la close maintenant right ?
