### ISSUE TITLE
Lorsque je reçois des notifications, je ne peux y accéder. * le screenshot n'a pas rapport

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#166]
**What happened:**
```
Lorsque je reçois des notifications, je ne peux y accéder. * le screenshot n'a pas rapport
```

**Version:** 3.0.0-beta (31026)

**Operating system:** Android 9

**Model:** ONEPLUS A6003

**Memory:** 65% (3.6 GB used out of 5.5 GB)

**Capacity:** 25% (12.5 GB used out of 49.6 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/24/awesome_logs) 

**Attachments:** 

![screenshot_1562606801794.png](http://buglife.s3.amazonaws.com/report_attachments/8189237982b005b8a5c718bed47adaa39a4f8401/original/screenshot_1562606801794.png?1562608052)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/24

Reported via Buglife

**Comment by Sonphil** [comment]
L'issue est redondante avec #189 et #190.
