### ISSUE TITLE
Profile text is white on white (discovery)

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#171]
**Describe the bug**
In the discovery, when launching from a dark theme, the student -> profile discovery text is absent or white on white.

**To Reproduce**
1. Launch the app for the first time with a dark theme set as system.
2. Follow the discovery up until the student page.
3. See the error

**Screenshots**

<details>
<summary>screenshot of discovery</summary>
<img width="450" src="https://user-images.githubusercontent.com/25663435/131251617-73e1f70b-7583-4097-9362-7626784aeba6.jpg" />
</details>

**Smartphone (please complete the following information):**
 - Device: samsung s10e
 - OS: Android

**Additional context**

**Comment by apomalyn** [comment]
There is the same issue with the icon on the more view. That should not be too complex to change 😄 if you could do it at the same time @guigui0609 😄 

<img width="344" alt="Screen Shot 2021-09-25 at 9 53 29 AM" src="https://user-images.githubusercontent.com/22211097/134773963-f84cd1c9-7ecd-48d2-bfc3-c69b26a25f49.png">

**Comment by apomalyn** [comment]
Just to do a little check. @guigui0609 are you still working on this issue? 😄 
Did you encounter any issues?

**Comment by guigui0609** [comment]
sorry I did not work much on the project lately :( I removed myself from the assignee
