### ISSUE TITLE
dans l'horaire, ce sont les dates de septembre qui sont affichés, malgré que jaie choisi l'onglet pour juillet.

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#171]
**What happened:**
```
dans l'horaire, ce sont les dates de septembre qui sont affichés, malgré que jaie choisi l'onglet pour juillet.
```

**Version:** 3.0.0-beta (30873)

**Operating system:** Android 9

**Model:** samsung SM-A530W

**Memory:** 78% (2.8 GB used out of 3.61 GB)

**Capacity:** 97% (23.6 GB used out of 24.2 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Disconnected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/26/awesome_logs) 

**Attachments:** 

![screenshot_1563384220251.png](http://buglife.s3.amazonaws.com/report_attachments/3b09a793f09459765da881f9a446c757de8022fd/original/screenshot_1563384220251.png?1563384327)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/26

Reported via Buglife

**Comment by Sonphil** [comment]
Fixed in #174
