### ISSUE TITLE
only next session sheddule is showing off

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#173]
**What happened:**
```
only next session sheddule is showing off
```

**Version:** 3.0.0-beta (31049)

**Operating system:** Android 9

**Model:** samsung SM-N960W

**Memory:** 55% (2.97 GB used out of 5.45 GB)

**Capacity:** 24% (26.7 GB used out of 111 GB)

**Locale:** Canada English

**Network:** 

**WiFi:** Disconnected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/27/awesome_logs) 

**Attachments:** 

![screenshot_1563902188117.png](http://buglife.s3.amazonaws.com/report_attachments/3bcedbc1db78dca9ae60ebcce495a4967bd51c4e/original/screenshot_1563902188117.png?1563902266)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/27

Reported via Buglife

**Comment by buzzben** [comment]
Update : spamming the scheddule tab randomly pull up the current and next session. When the next session is active, there is no way to rollback to the previous session unless the page is recharged and the current session is randomly shown

**Comment by buzzben** [comment]
Update : recharging the page by scrolling up can trigger the dates at the top to update with the current date without updating the detailled page, causing a mismatch between the shown date and detail. Again, random but recurrent behaviour.

**Comment by Sonphil** [comment]
@buzzben The schedule has been updated. Are you able to see your current and next session now?

**Comment by buzzben** [comment]
@Sonphil New schedule pretty neat! No more bugs. Huge thanks. Only place for improvement on display & practicality side now. :)

**Comment by Sonphil** [comment]
@buzzben Which improvement would you like? :)

**Comment by Sonphil** [comment]
I will close the issue now since the problem has been fixed in #174.
