### ISSUE TITLE
Week view in schedule tab

### ISSUE THREAD

**Issue by buzzben** [ApplETS/Notre-Dame#175]
Improvement for schedule tab
1- much like the week view on the "my ets" web page summary, having this feature available in the schedule tab would be awesome. Seeing a single day makes the events (classes) take the entire most of the place and isn't as practical. It is also redundant with the dashboard display and makes it less likely to be the tool of choice for a daily overview. Like most schedulers, a way to see an overview of the week or month is a feature the app should offer.
![Screenshot_20190725-125245_Chrome](https://user-images.githubusercontent.com/5466030/61893040-25fe3b80-aedb-11e9-9eb0-0a4825d7570c.jpg)

**Comment by Sonphil** [comment]
Thank you for your suggestion @buzzben!

**Comment by Sonphil** [comment]
This is is easily diable. The `WeekView` has [numberOfVisibleDays](https://github.com/ApplETS/Notre-Dame/blob/c0b6b3ad331e2003290f3963c28f778569f2317c/android/app/src/main/res/layout/fragment_schedule.xml#L37) property that can be set programmatically.

**Comment by buzzben** [comment]
Awesome solution! 4 days view works the best for me in portrait mode, a full week in landscape. Hopefully, once the app is more final, this could be presets. I dont believe the end-user really need all that control.
