### ISSUE TITLE
Scrolling inertia fix in schedule view

### ISSUE THREAD

**Issue by buzzben** [ApplETS/Notre-Dame#176]
Scrolling between days inertia and snap to day in schedule view is too sensitive and feels like it doens take the scrolling speed of the input into account.
Making the snap more agressive and matching the input speed would improve user experience while scrolling horizontally from one date to the next/nexts.

**Comment by Sonphil** [comment]
The WeekView has [xScrollingSpeed](https://github.com/ApplETS/Notre-Dame/blob/c0b6b3ad331e2003290f3963c28f778569f2317c/android/app/src/main/res/layout/fragment_schedule.xml#L52) property. We could let the user change it.
