### ISSUE TITLE
Mark a activity as a evaluation

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#181]
**Is your feature request related to a problem? Please describe.**
As a student, I would like to be able to mark an activity in the schedule as an examen (like a quiz, intra or final).

**Describe the solution you'd like**
In the schedule, I long touch an activity, a bottom sheet appears where I can choose to mark the activity as 'Quiz', 'Intra' or 'Final'. That could also be interesting to have a space where the student can add a description.

**Comment by MysticFragilist** [comment]
Est-ce qu'on veut un API ou stocker en local?  (question ouverte)

**Comment by MysticFragilist** [comment]
Les examens sont maintenant indiqué à même la carte de calendrier. Je ferme ceci! :)
