### ISSUE TITLE
On peut pas changer la langue 

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#182]
**What happened:**
```
On peut pas changer la langue 
```

**Version:** 3.0.0-beta (31049)

**Operating system:** Android 7.0

**Model:** samsung SM-G920F

**Memory:** 79% (2.08 GB used out of 2.62 GB)

**Capacity:** 87% (22 GB used out of 25.3 GB)

**Locale:** Canada English

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/28/awesome_logs) 

**Attachments:** 

![screenshot_1564511457507.png](http://buglife.s3.amazonaws.com/report_attachments/291722626a0d65bac9d2d6aaea1114fc7ec07815/original/screenshot_1564511457507.png?1564511535)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/28

Reported via Buglife

**Comment by Sonphil** [comment]
Redondant avec l'issue #192
