### ISSUE TITLE
Intégration d'un lien vers l'Heuristique dans la section ETS

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#183]
** Feature asked **
De la même manière que l'application propose des cards pour Moodle, MonETS, Bibliotech, etc... l'Heuristique souhaite être ajouté dans la liste. 

Leur logo a été transmis, pret pour intégration

**Comment by Sonphil** [comment]
@apomalyn Serait-il possible d'attacher le logo à l'issue?

**Comment by apomalyn** [comment]
J'ai demandé une modification de leur part étant donnée que le SVG fournit avait des zones blanches encore a des endroits non voulu. Je l'upload ici des que fini.
