### ISSUE TITLE
Peut pas login

### ISSUE THREAD

**Issue by grindcore819** [ApplETS/Notre-Dame#186]
**Describe the bug**
Je ne peux pas me logger sur mon application avec la nouvelle mise à jour

**To Reproduce**
1. Ouvrir l'aplication
2. Entrer ses credentials
3. recevoir un message d'erreur

**Expected behavior**
Devrait pouvoir me logger

**Screenshots**
![Screenshot_20190807-130217_TSMobile bta](https://user-images.githubusercontent.com/5703729/62643329-bbef8880-b915-11e9-97db-20e87e248f79.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung a70
 - OS: Android 9
 - Browser Chrome
 - Version latest stable

**Additional context**
(Add any other context about the problem here.)

**Comment by Sonphil** [comment]
@grindcore819 Pourrais-tu mettre à jour ton application une nouvelle fois?
https://github.com/ApplETS/Notre-Dame/commit/657e1841660864f08a8104bbc30c38f83fb07a12 devrait avoir réglé ce problème.

**Comment by grindcore819** [comment]
merci @Sonphil, c'est réglé
