### ISSUE TITLE
[IMPOSSIBLE TO REPRODUCE] Issue from  

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#199]
**Describe the issue** 
```il ya un bug quand on ouvre les documents. après quelques secondes la page se rafraîchit toute seule et le document remonte à la première page. Assez compliqué de travailler ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-757270578.png?raw=true)

**Device Infos** 
- **Version:** 4.2.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631833857 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.7.1

**Comment by apomalyn** [comment]
@ApplETS/general maybe someone understands the problem??

**Comment by apomalyn** [comment]
Maybe, we should test in both platform to be sure. @camillebrulotte @JonathanDuvalV could you test in iOS please?

**Comment by camillebrulotte** [comment]
Not sure how to reproduce it.. The quicklinks seems to work fine.

**Comment by camillebrulotte** [comment]
J'ai ouvert un document pdf à partir du quicklink MonEts mais ça fonctionne bien.

**Comment by apomalyn** [comment]
Impossible to reproduce the bug...will close it for now.
