### ISSUE TITLE
Design and implement 'Not found' page

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#2]
**Is your feature request related to a problem? Please describe.**
We should have a proper page if the navigation fails.

**Describe alternatives you've considered**
Creating a simple page who offer to redirect on the home screen of the application.

**Comment by priyanshu0405** [comment]
Hey @apomalyn, can I take this issue? Thanks!!

**Comment by apomalyn** [comment]
@priyanshu0405 Of course! :)
