### ISSUE TITLE
Unify the refresh behaviour

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#201]
**Describe the issue** 
```Quand ont scroll vers le bas pour actualiser l’horaire il n’y a pas de « throbber » tel que dans profil.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-500870426.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.8

**Comment by apomalyn** [comment]
We should unify the refresh behaviour. Add the same system as the grades or profile into the schedule.
