### ISSUE TITLE
Option to export the calendar

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#202]
**Describe the issue** 
```L’export du calendrier serait une très bonne fonctionnalité à ajouter.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-661284601.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.8

**Comment by XavierPaquet-Rapold** [comment]
Duplicated with #783
