### ISSUE TITLE
Rating because we have a beautiful app!

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#206]
**Is your feature request related to a problem? Please describe.**
As a student who loves this application, I would like to be reminded that I can rate the app in the store!

**Describe the solution you'd like**
After some time of use, we could ask the user if he/she likes the app and if so he/she would like to add a review

**Additional context**
Plugins: 

- [in app review](https://pub.dev/packages/in_app_review)

**Comment by apomalyn** [comment]
Just to do a little check. @camillebrulotte are you still working on this issue? 😄 Do you need help?

**Comment by camillebrulotte** [comment]
> Just to do a little check. @camillebrulotte are you still working on this issue? 😄 Do you need help?

Ouii je l'avais commencé mais maintenant j'essaye plus de fix ma pr avant de m'y remettre dessus. :D Mais le temps manque un peu 😅 Honnêtement je sais pas si j'aurais le temps de la compléter avant la fin de la session. Donc si c'est elle urgente quelqu'un d'autre peut la prendre sans prob ! Autrement, c'est certain que je la clanche dès que je finis mon dernier exam final. :)
