### ISSUE TITLE
[Schedule] Add a view to see the complete schedule weekly

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#211]
**Describe the issue** 
```est-il possible d’avoir un bouton pour avoir l’horaire d’une semaine au complet?```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-804192279.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.7.1

**Comment by MysticFragilist** [comment]
There are 3 different persons that requested that feature to me. I'll assign that as a priority-high for now! 😄
