### ISSUE TITLE
Median is not on a percent scale

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#214]
**Describe the issue** 
```dans la case median du haut, la médiane est afficher en pourcentage, faudrait mettre juste le nombre (ex: 22) ou bien mettre le pourcentage réel (ex: 22/30 %).```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-506407365.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.0

**Comment by MysticFragilist** [comment]
We should see the `Median` as a percentage not a sum of every percent.
