### ISSUE TITLE
L'horaire n'affiche pas les séances de cours du 30 septembre

### ISSUE THREAD

**Issue by Sonphil** [ApplETS/Notre-Dame#216]
L'horaire ne présente aucune séance de cours le 30 septembre alors que MonÉTS oui.

Issues similaires : 
#213 
#212

**Comment by Sonphil** [comment]
Yo @apomalyn As-tu ce problème aussi? Est-ce que les séances de cours de cette journée s'affichent dans l'ancienne app?

**Comment by apomalyn** [comment]
Sup' @Sonphil ! Yep j'ai le même soucis, alors que l'ancienne affiche correctement l'horaire.
