### ISSUE TITLE
Grades are at 0 % on evaluation tiles

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#217]
**Describe the issue** 
```all the grades are at 0%```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-508953255.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.0.1

**Comment by apomalyn** [comment]
I don't see anything in the analytics linked to this...For now, we will keep this around if someone else finds something similar.
