### ISSUE TITLE
Bogue au niveau de l'affichage de l'horaire. Le cours du soir est affiché au-dessus de celui du matin (normalement, c'est l'inverse)

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#218]
**What happened:**
```
Bogue au niveau de l'affichage de l'horaire. Le cours du soir est affiché au-dessus de celui du matin (normalement, c'est l'inverse)
```

**Version:** 3.0.0-beta (30733)

**Operating system:** Android 6.0.1

**Model:** samsung SM-G900V

**Memory:** 71% (1.19 GB used out of 1.67 GB)

**Capacity:** 92% (9.71 GB used out of 10.5 GB)

**Locale:** United States English

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/34/awesome_logs) 

**Attachments:** 

![screenshot_1569274488897.png](http://buglife.s3.amazonaws.com/report_attachments/b99205c876fb0b622dfa712e9dcb64bcb2f55db6/original/screenshot_1569274488897.png?1569274824)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/34

Reported via Buglife

**Comment by apomalyn** [comment]
Already fixed
