### ISSUE TITLE
[Schedule] Allow changing starting day of week

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#22]
**Describe the solution you'd like**
As a user, I would like to change the starting day of the week.

**Additional context**
Currently, the calendar package we are using doesn't support the change of startingDayOfWeek at runtime.
Will be resolved when: https://github.com/aleksanderwozniak/table_calendar/issues/164

**Comment by apomalyn** [comment]
🎉 🎉  The feature will be added in the 3.0.0 version of table_calendar!!! 🎉 🎉 

We will be able to support this feature when null safety 😄

**Comment by MysticFragilist** [comment]
If it's good with you @apomalyn, I'll start with this issue, as it will be required to do #68 😄

**Comment by apomalyn** [comment]
You are good to go! 😄 if possible check if you can solve #92 at the same time
