### ISSUE TITLE
Opening a pdf in moodle is not stable

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#222]
**Describe the issue** 
```dans un de mes cours Moodle (MAT472) les PDF du cours ne peuvent pas s’ouvrir sur l’application un message d’erreur apparaît (même chose sur Safari sur iPhone)```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-424230943.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.6

**Comment by MysticFragilist** [comment]
Do you guys think it would be the same as this issue that we couldn't understand maybe? #199

**Comment by AntoineLemelin** [comment]
I'm not able to reproduce the problem...
