### ISSUE TITLE
Improve visibility of each update.

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#231]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be informed when a new version of the application is released.
Some users disable automatic updates on their phones and so aren't notified when a new version is available.

**Describe the solution you'd like**
For starters, we could automatically publish a tweet, Facebook message, Reddit post when a release is published using actions like these: [Tweet to Twitter](https://github.com/marketplace/actions/tweet-to-twitter), [Facebook Notify](https://github.com/marketplace/actions/facebook-notify).

**Comment by apomalyn** [comment]
I do agree with you. Saturday I will write everything we need to start working on What's new 😄

**Comment by MysticFragilist** [comment]
Closing this since we have the popup notification in app!
