### ISSUE TITLE
When i log in, nothing loads. Weirdly, it also happens with the older version of this app. It all started not behaving on Wednesday december 4th. No clue what caused it.

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#232]
**What happened:**
```
When i log in, nothing loads. Weirdly, it also happens with the older version of this app. It all started not behaving on Wednesday december 4th. No clue what caused it.
```

**Version:** 3.0.0-beta (31245)

**Operating system:** Android 6.0

**Model:** LGE LG-H812

**Memory:** 82% (2.27 GB used out of 2.77 GB)

**Capacity:** 68% (15.5 GB used out of 22.7 GB)

**Locale:** Canada English

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/38/awesome_logs) 

**Attachments:** 

![screenshot_1575643133132.png](http://buglife.s3.amazonaws.com/report_attachments/40690f9d41501419f34c391a88f73df7d1a3b292/original/screenshot_1575643133132.png?1575643353)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/38

Reported via Buglife

**Comment by apomalyn** [comment]
Très probablement un cas de compte bloqués pour session impayés, la date ferais du sens
