### ISSUE TITLE
Le popup pour demander de reporter un bug revient tout le temps lorsque j'appuie sur "Cancel". Le problème vient d'apparaître, aujourd'hui.

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#233]
**What happened:**
```
Le popup pour demander de reporter un bug revient tout le temps lorsque j'appuie sur "Cancel". Le problème vient d'apparaître, aujourd'hui.
```

**Version:** 3.0.0-beta (31245)

**Operating system:** Android 10

**Model:** Google Pixel 3a XL

**Memory:** 67% (2.35 GB used out of 3.51 GB)

**Capacity:** 23% (11.4 GB used out of 50 GB)

**Locale:** Canada English

**Network:** 

**WiFi:** Disconnected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/39/awesome_logs) 

**Attachments:** 

![screenshot_1576690889555.png](http://buglife.s3.amazonaws.com/report_attachments/10d0a06ca2c83c3ee4a63caafcc95ccbbf9199e2/original/screenshot_1576690889555.png?1576691421)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/39

Reported via Buglife

**Comment by apomalyn** [comment]
A ignorer voir #234
