### ISSUE TITLE
Add device name to the issue reported

### ISSUE THREAD

**Issue by AlexandreMarkus** [ApplETS/Notre-Dame#236]
**Is your feature request related to a problem? Please describe.**
I would like to know what is the name of the device.
ex: Pixel, Iphone...

**Comment by apomalyn** [comment]
@AlexandreMarkus that could be a part of #177 
If you want to have other issues to work on (after this one), check the [Kanban](https://github.com/ApplETS/Notre-Dame/projects/13) project please 😄
