### ISSUE TITLE
Grade button widget have wrong grade value

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#249]
**Describe the issue** 
```J'ai reçu des notes en MAT350 et PHY332 mais aucune d'entre elles ne s'affichent sur la page grades. Bien qu'ils soient à jours et fonctionnelle sur les pages de détails```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-884291412.png?raw=true)

**Device Infos** 
- **Device:** SM-G970W 
- **Version:** 4.4.5 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1634626140 
- **Platform operating system:** android 
- **Platform operating system version:** RP1A.200720.012.G970WVLU6GUH5

**Comment by apomalyn** [comment]
> Yuppp @apomalyn I just tested the cache removal and it also did nothing on my friend phone... It seems like deleting the cache is not the problems, it needs to remove every bit of storage to fix the issue this is really problematic...

Yeah...I think this is because of shared preferences...maybe because there is still some String that should be boolean...maybe we should force logout everyone on the next update or add a little logic to force clean the preferences...idk 😅
