### ISSUE TITLE
"An error has occurred" appears in grade details when there is no summary

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#267]
**Describe the issue** 
```The message "An error has occurred" is displayed when opening a course without summary. This is not really  bad but we will have to fix this```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-650479112.png?raw=true)

**Device Infos** 
- **Device:** Pixel 2 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1634853217 
- **Platform operating system:** android 
- **Platform operating system version:** RP1A.201005.004.A1

**Comment by camillebrulotte** [comment]
Duplicate #194

**Comment by camillebrulotte** [comment]
oh right I thought it was the "No grade available" but the screenshot is not related.
