### ISSUE TITLE
Can't open app anymore

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#275]
**Describe the issue** 
```bonjour, suite à ma mise à jour sur iPhone 8, je n’arrive pas à ouvrir l’application ÉTS. Pouvez vous fixer le bogue? merci beaucoup ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-99017278.png?raw=true)

**Device Infos** 
- **Device:** iPad13,8 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1634853831 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.5.1

**Comment by apomalyn** [comment]
There was no other report of this so I close it.
