### ISSUE TITLE
Red corners showing up in schedule settings bottom sheet and make the bottom sheet bigger

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#276]
**Describe the bug**
When scrolling down the bottom sheet, you can see red corners at the top due to items that are "selected". Also, make the bottom sheet bigger when there is activity selection displayed.

**To Reproduce**
1. Go to Schedule
2. Click on the gear icon (to open the schedule settings)
3. Scroll down

**Expected behavior**
We should not see the red corners when scrolling down.

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/37625944/138563297-0861d674-7055-4f41-8201-52b039d58894.png">

**Comment by eneiss** [comment]
@camillebrulotte what device did you use to get this bug? I just tried to reproduce it on my Samsung A41 but I don't have any red corners on the bottom sheet.
Did it get fixed in a previous release ? (I'm on 4.7.0)
<img src="https://user-images.githubusercontent.com/33004979/152597596-d0992050-f21c-4b65-b399-ca7a53e7c3fe.jpg" width="400">

**Comment by apomalyn** [comment]
@eneiss continue to scroll a bit 😄 the problem appears when a selected tile is completely behind the title (behind 'Parametres de l'horaire')

**Comment by eneiss** [comment]
> @eneiss continue to scroll a bit 😄 the problem appears when a selected tile is completely behind the title (behind 'Parametres de l'horaire')

I can't scroll any further though, so I guess the bug won't appear on a 20:9 screen then 🤷

**Comment by XavierPaquet-Rapold** [comment]
Doesn't seem to be a problem anymore as of v4.21.5

**Comment by MysticFragilist** [comment]
J'suis capable de reproduire sur mon device:

![image](https://github.com/ApplETS/Notre-Dame/assets/25663435/5f830c36-a2ca-436c-847a-cb51c14f07ab)

**Comment by LouisPhilippeHeon** [comment]
Done in #899
