### ISSUE TITLE
Add a save button in the schedule settings

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#278]
**Describe the solution you'd like**
There should be a 'Save' button in the bottom sheet of the schedule settings. When tapping 'Save' everything is registered and applied, the sheet should close itself and if the user closes the bottom sheet without saving, everything is discarded.

**Comment by MysticFragilist** [comment]
Dans le cas d'un drawer on ne voit pas l'utilitee.
