### ISSUE TITLE
Duplicate courses in dashboard card

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#280]
**Describe the issue** 
```Avant mon cours de mec788 avait "disparu". J'ai désinstallé et réinstallé. Maintenant, j'ai 2x  mec402 et 2x mec788.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-584030588.png?raw=true)

**Device Infos** 
- **Device:** BBB100-1 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1634853217 
- **Platform operating system:** android 
- **Platform operating system version:** ABP819

**Comment by hadi4172** [comment]
Même problème sur iOS, un truc pour aider à faire apparaitre ce bug est d'appuyer plusieurs fois rapidement sur le bouton Accueil

**Comment by apomalyn** [comment]
@hadi4172 ça arrive toujours avec la 4.6.2? Ou tu es sur la 4.4.8 aussi?

**Comment by hadi4172** [comment]
Oui je suis sur la 4.6.2

**Comment by MysticFragilist** [comment]
duplicate of #357
