### ISSUE TITLE
Indicate the user when a new version is available

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#282]
**Is your feature request related to a problem? Please describe.**
As a student, I would like to be inform when a new version of the application is available. 

As a maintainer, I would like the user to migrate as quickly as possible to the latest version.

**Describe the solution you'd like**
I thought about something like that: 

![Screenshot_20211029-083204.png](https://user-images.githubusercontent.com/22211097/139435402-c7d8c745-2be2-457c-9d5b-4e2d05c9b9e5.png)

(Sorry for the size of the image, I'm writing this on mobile 😅)

**Additional context**

We could use [Flutter Siren](https://pub.dev/packages/flutter_siren) for example ^^

**Comment by MysticFragilist** [comment]
@apomalyn I'm waiting for my PR on flutter_siren to be merged and made available. For more info on the issue I had go check out: https://github.com/diegocosta/flutter_siren/pull/8. So currently I have two screens that are prompted. 
There is the Ask for update:
![image](https://user-images.githubusercontent.com/25663435/139601083-6dd5dc14-3191-41a4-a6bd-ed7804341a25.png)

And the force update:
![image](https://user-images.githubusercontent.com/25663435/139601043-c65553ab-bf90-4b2d-974b-3d05aeb2d4eb.png)

The `ask update` is triggered by a change to a minor or a major version. This is made for an informative purposes to let the user know there is a new update. As the `force update` is when there is a patch (or revision) change. This is to force users to download bugfix for a major or minor version. 

LMK what you think about the alert, I don't find them that ugly but I can still do custom ones if you insist. :smile
