### ISSUE TITLE
Quit web page error

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#289]
**Describe the issue** 
```Lorsqu'on quitte une page internet ouverte dans l'appli (ex.: Moodle), l'application se ferme et met un message que l'application a cessé de fonctionner. version Android. Merci!```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-94061409.png?raw=true)

**Device Infos** 
- **Device:** SM-G970W 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1634853217 
- **Platform operating system:** android 
- **Platform operating system version:** RP1A.200720.012.G970WVLS6GUJ1

**Comment by MysticFragilist** [comment]
#88

**Comment by MysticFragilist** [comment]
Linked to #304
