### ISSUE TITLE
Use secured storage to store user information

### ISSUE THREAD

**Issue by kevinstsauveur** [ApplETS/Notre-Dame#3]
**Is your feature request related to a problem? Please describe.**
It may already be your intention but it would be mandatory to store user info into secured storage for both Android and IOS.

**Describe the solution you'd like**
Store sensitive information securely.

**Describe alternatives you've considered**
A package [exist](https://github.com/mogol/flutter_secure_storage) for flutter that uses the following:

> [Keychain](https://developer.apple.com/documentation/security/keychain_services#//apple_ref/doc/uid/TP30000897-CH203-TP1) is used for iOS
> AES encryption is used for Android. AES secret key is encrypted with RSA and RSA key is stored in [KeyStore](https://developer.android.com/training/articles/keystore.html)

I don't know how _Notre-Dame v3_ is working but using what each OS is recommending should be the way to go.

**Comment by apomalyn** [comment]
Thanks, @kevinstsauveur! Normally someone from the club sent you an email so you can join us! 
Yes, we saw this package and want to use it. Good catch 😄 

Currently, we are finishing the preparation for really starting the development that includes creating all the issues for the MVP.
