### ISSUE TITLE
Crash repeatedly from chrome custom tab

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#304]
**Describe the bug**
I don't know if this is prevented safely handled, but it seems that a lot of user can't open the app due to a crash occurring in the package: `flutter_inappwebview`. It would be important to investigate this issue, but I don't know if this is reproducible it seems like it is trigger at random.

<details>
  <summary>Error log</summary>
  <pre>
  <code>
<b>Fatal Exception: java.lang.RuntimeException Unable to start activity</b>     
ComponentInfo{ca.etsmtl.applets.etsmobile/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException:
Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
  </code>
  </pre>
</details>

**To Reproduce**
?

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/25663435/142000521-32edf75e-7f80-4c0b-a5ef-a244cee0a58f.png)

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/25663435/142002371-0c029bc0-10e6-44df-9af6-c33c85463c59.png)

**Additional context**
It seems like we are not alone with this mystery bug:
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1031
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1009
https://github.com/pichillilorenzo/flutter_inappwebview/issues/801

**Comment by apomalyn** [comment]
That should have been handled normally but it's possible the exception is still logged. Check if that still occurs in 4.6.0. That should have been fixed with #268

**Comment by AlexandreMarkus** [comment]
#254 you can find the explanation in there (chrome is not installed on these devices). As @apomalyn mentioned, the log should not happen anymore.

**Comment by MysticFragilist** [comment]
It still occurring in 4.6.0. But it seems like it come internally from the package that we use. It's a java exception. Also, look at #289 there is an actual person that his app is crashing completely...

**Comment by MysticFragilist** [comment]
Okay, so by reading a bit of the issues in the package, there is three possibles choices we could do:
We could revert to a previous version (The crash seems to be an old issue that was fixed but came back in the recent version)
Or
We could wait for a package fix from the maintainer (This could potentially be long as it has over 350 issues and the maintainer seems to not be able to keep up)
Or
We could change the package to another in app web view (I've seen three different package)

**Comment by apomalyn** [comment]
I don't really know for sure...maybe @AlexandreMarkus can answer that?

**Comment by AlexandreMarkus** [comment]
> I don't really know for sure...maybe @AlexandreMarkus can answer that?

@MysticFragilist @apomalyn  yes there is a reason why. I think we should do a quick meeting to discuss about it to make sure we are on the same page ;)

**Comment by MysticFragilist** [comment]
Okay! Yes that would be good I think! When are you available?

**Comment by AlexandreMarkus** [comment]
> Okay! Yes that would be good I think! When are you available?

During the weekend would be good. Also, I fond out there is other plugin that gives the same feature available: https://pub.dev/packages/flutter_web_browser https://pub.dev/packages/flutter_custom_tabs
