### ISSUE TITLE
H/S not written appropriately

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#326]
**Describe the issue** 
```pourquoi je n’ai pas de note pour le cours de math144 et phy144? aussi que veut dire H/S pour ATE029```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-268776185.png?raw=true)

**Device Infos** 
- **Device:** iPhone13,2 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1637281198 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.8.1

**Comment by MysticFragilist** [comment]
Ceci est probablement relié au fait que les évaluations pour les professeurs n'ont pas été remplis. Il suffit de se diriger vers signets pour les faire.

**Comment by MysticFragilist** [comment]
Je vois par contre qu'il y a "H/S" et "H/" comme note, il y a-t-il un problème d'affichage?

**Comment by apomalyn** [comment]
Non, "H/S" est pour "Hors programme/Success", tandis que "H/" est pour un cours Hors programme qui n'a pas encore de côte. Le problème avec les cours hors programme c'est qu'ils ont une côte même si ce cours n'a pas encore de cote disponible.

**Comment by MysticFragilist** [comment]
D'accord! Ça répond à ma question dans ce cas! :smile:

**Comment by apomalyn** [comment]
Fait plaisir 😉
