### ISSUE TITLE
Downgrade minimum supported iOS version to 12

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#330]
**Describe the bug**
Some iPhone users have reported that the application crash on boot on iOS 13.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS13
 - Version 4.6.2

**Additional context**
Look at the firebase crashlytics around 19h 48min 45s the 26 November 2021. A user with the problem opened the application

**Comment by MysticFragilist** [comment]
Here are all the stats for the last 24h:
![image](https://user-images.githubusercontent.com/25663435/143665198-a11c3485-84a8-40d7-a154-89d8f99436da.png)
There doesn't seem to have been any events coming from iOS13 (only iOS14 and iOS15 are displayed):
![image](https://user-images.githubusercontent.com/25663435/143665335-9d465767-d900-4423-a77a-85bfadab9f64.png)

Maybe the crash occurs before the app is fully loaded and crashlytics gets instantiated?

**Comment by apomalyn** [comment]
mmmmh maybe we have a problem with the compilation (target deployment maybe :thinking:) we could check if the app is loading on iOS 13 (using the simulator)

**Comment by MysticFragilist** [comment]
I think I tested that 2 weeks back when I was doing #307 on the Mac and it was working well with iOS13. I can retest it with the new version (4.6.2) next time I'm around. I'll try to use a release version just to make sure!

**Comment by AlexandreMarkus** [comment]
> I just checked the version and turns out, it only support iOS 14 minimum this should probably help users that don't have a cutting edge phone. There some people that sent me emails about this problem too.

I think that some plugins we use need a minimum IOS and Android version. Make sure that all plugins are working ;)

**Comment by MysticFragilist** [comment]
Yes exactly! We will probably need to change some packages for them to work from a minimum of iOS 12. If there is some missing functionality in a new package we could also create an `adapter` folder to offload the switching between the old library and the new one depending on the version. 😄

**Comment by AlexandreMarkus** [comment]
> Yes exactly! We will probably need to change some packages for them to work from a minimum of iOS 12. If there is some missing functionality in a new package we could also create an `adapter` folder to offload the switching between the old library and the new one depending on the version. 😄  

Good idea!
