### ISSUE TITLE
MonÉTS not available outside the school

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#335]
**Describe the issue** 
```je n’ai plus accès à monEts de la maison```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-297263125.png?raw=true)

**Device Infos** 
- **Device:** iPhone10,4 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1634853831 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.8

**Comment by apomalyn** [comment]
It's because the school moved all the services behind the VPN. We can't do anything for now about that, but I will let this one open for now until we find a solution with the IT school department

**Comment by MysticFragilist** [comment]
After talking with Christian, nothing can be done on our side closing this.
