### ISSUE TITLE
Discovery always appear when launching the app

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#353]
**Describe the issue** 
```Every time I open the app I get the tutorial again and it’s pretty annoying to daily usage.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-284620644.png?raw=true)

**Device Infos** 
- **Device:** iPad11,3 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1637281198 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.1

**Comment by MysticFragilist** [comment]
Also maybe worth checking for the screenshot resolution of the bug reported image for Ipad

**Comment by camillebrulotte** [comment]
Personnellement je n'ai jamais eu l'issue sur mon iPad ... Je ne vois pas trop ce qui pourrait causer cela puisque le seul moment où le Discovery s'affiche est lorsque la cache est vidé (par logout par exemple).

**Comment by MysticFragilist** [comment]
duplicate of #394 (which is furthermore explained)
