### ISSUE TITLE
MonETS quicklink login page

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#355]
**Describe the issue** 
```impossible d'accéder au portail depuis l'application. Sur Android 12, les champs textes pour le nom d'utilisateur et mot de passe ne font pas apparaître le clavier et c'est donc impossible de se connecter```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-128848482.png?raw=true)

**Device Infos** 
- **Device:** Pixel 4a (5G) 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1637280951 
- **Platform operating system:** android 
- **Platform operating system version:** SQ1A.211205.008

**Comment by camillebrulotte** [comment]
Personnellement je n'ai pas le problème sur Iphone.

**Comment by AntoineLemelin** [comment]
I'm not able to reproduce this problem I'm on android 12 and I don't have any problem. I think we should close this thread.
