### ISSUE TITLE
Reload button in Dashboard page

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#357]
**Describe the issue** 
```Appuyez plusieurs fois sur le bouton « reload » sur l’accueil multiplie les entrées de cours dans a section « notes »```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-222666660.png?raw=true)

**Device Infos** 
- **Device:** iPhone10,4 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1637281198 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.1

**Comment by Bretzoule** [comment]
J'ai reproduis sur Android aussi (Emulateur Pixel 3A), j'vais prendre l'issue et investiguer dessus ! 
![bug](https://user-images.githubusercontent.com/69150827/150690860-9b8cefed-c88a-400a-9cf1-fde791958c38.gif)
