### ISSUE TITLE
Schedule and course empty for someone

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#360]
**Describe the issue** 
```j’arrive pas a voir mes cours et mes horaires !! rien n’est affiché ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-410108747.png?raw=true)

**Device Infos** 
- **Device:** iPhone14,2 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1637281198 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.1.1

**Comment by MysticFragilist** [comment]
Ceci arrive à plusieurs personnes... C'est le problème de cache récurrent qui empêche de voir certaines informations. Il faut vraiment voir à ça
