### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by michaudm** [ApplETS/Notre-Dame#366]
Opened the application and realised I'd been logged out.
Tried to login, but when I click "Se connecter" the password field gets cleared and the form complains that the password field is empty. Any attempt to login yields the same result.

Reinstalling the application does not solve the problem...
And according to reviews on Google Play, I'm not the only one.

**Comment by VincentAudette** [comment]
There is an issue with the connection to the authentication server. We've been in contact with the IT department to get the solution fixed. The issue will be fixed as soon as possible.
