### ISSUE TITLE
Keyboard doesn't show on quicklick tabs

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#376]
**Describe the issue** 
```Le clavier ne s’affiche pas quand je veux me connecter à mon ets```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-462822268.png?raw=true)

**Device Infos** 
- **Device:** iPad5,1 
- **Version:** 4.6.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1637281198 
- **Platform operating system:** ios 
- **Platform operating system version:** 15.2.1

**Comment by MysticFragilist** [comment]
Can somebody with an Ipad test this issue and see if it's reproducible? 😄

**Comment by MysticFragilist** [comment]
Also wait, somebody was able to connect???

**Comment by MysticFragilist** [comment]
potentially closed by #374, will keep an open eye on that one

**Comment by MysticFragilist** [comment]
duplicate
