### ISSUE TITLE
Add Moodle connexion persistency

### ISSUE THREAD

**Issue by robinmarce** [ApplETS/Notre-Dame#391]
When a user clicks on Moodle, he is redirected to the home page of Moodle but he has to connect each time.

It would be way more user friendly to enable the connexion persistency and keep the user signed in even if he closes the browser or the application.

**Comment by MysticFragilist** [comment]
It's a great idea! Though I'm not sure if it's possible as it uses the School SSO page. It will have to be investigated first before doing anything.

**Comment by AntoineLemelin** [comment]
To keep the connection up we need to keep in memory the connection cookie of outlook. I'm not really sure if we can do that with a WebView...

**Comment by MysticFragilist** [comment]
Régler depuis la nouvelle webview
