### ISSUE TITLE
Make the profile section more accessible

### ISSUE THREAD

**Issue by robinmarce** [ApplETS/Notre-Dame#392]
### **Problem**
The grades section is accessible at 2 different spots of the application (dashboard & Student).
The profile section is accessible only in the student section under the tab Profile. It feels like a hidden section because the user has to click twice to display the information.

### **Solution**
**_1st proposition_** : Set Profile as the default tab because the grades are already easily accessible in the dashboard
**_2nd proposition_** : Remove the tabs and merge them into a single student section with grades and student informations

**Comment by MysticFragilist** [comment]
This, I'm not sure anymore, maybe we can have some more inputs on this @ApplETS/general ?

I think a single page wouldn't be that ergonomic as we would have to scroll so far to get the info so I'm not sure about this solution. For the first proposition, I know I'm the one that told it (lol) but I'm not sure people use more profile than grade. Essentially, the first page you're shown to, should be the page people use the most to prevent user having to make another tap. I personally always use the page student to see my grade I don't pass so much from the dashboard.

**Comment by MysticFragilist** [comment]
Après analyse, on a déterminer que la page de notes est plus utilisé/importante que profil. Nous allons, donc fermé cette issue.
