### ISSUE TITLE
Add user feedback on go back to now button in the schedule

### ISSUE THREAD

**Issue by robinmarce** [ApplETS/Notre-Dame#393]
I didn't understand what was the purpose of the button next to the schedule settings button.
I clicked on it several times without understanding it.

I think a user feedback (a toast for instance) would be appreciated if the user clicks on it while being on the schedule of the current period (when this button is pointless because it means the user doesn't know its purpose if he clicks on it in this case)

**Comment by MysticFragilist** [comment]
This is a great idea! :smile:
