### ISSUE TITLE
Log out + log in launches the tutorial

### ISSUE THREAD

**Issue by robinmarce** [ApplETS/Notre-Dame#394]
I tried to log out and log in again and I had the surprise to be onboarded again with an application tour.

A solution could be a button to launch the tutorial at any time in the section "more" and propose the tutorial on login only if it is the first connexion after the installation.

Let's imagine a situation. I am with a friend from LOG450. We heard the grades are online but my friend is out of battery. He has to connect with my phone and is really excited about his grades. He wants to know them quickly. I log out and he logs in and the tutorial appears. When I switch back to my account it appears again.

**Comment by Bretzoule** [comment]
Lorsque tu termines le guided_tour, tu set une variable dans le local storage qui empêche ce tour de redémarrer. Quand on se déconnecte on clear ce local storage, voilà pourquoi le guided tour redémarre (enfin je crois que c'est pour ça, si je dis des bétises faudra m'expliquer car j'ai manqué quelque chose lol). 

Ce n'est donc pas "normal" mais ce n'est pas vraiment un bug, c'est le comportement normal, qu'il faudrait peut-être changer, je suis d'accord.

**Comment by robinmarce** [comment]
Est ce qu'on pourrait pas clear le local storage et reset immédiatement la variable guided_tour dans le local storage ?

**Comment by AlexandreMarkus** [comment]
> Est ce qu'on pourrait pas clear le local storage et reset immédiatement la variable guided_tour dans le local storage ?


Oui, ça serait effectivement la façon de faire
