### ISSUE TITLE
Pull to refresh page happens if we change quickly to grade detail after a storage reset

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#401]
**Describe the issue** 
```If I reset the storage of the app, and go straight to the grades view I see the "pull to refresh screen" instead of a loading. if I wait long enough the view refresh and my grades are shown. it's not a bug but more like a behavior concern```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-881698404.png?raw=true)

**Device Infos** 
- **Device:** Pixel 6 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1645466811 
- **Platform operating system:** android 
- **Platform operating system version:** SQ1D.220205.004

**Comment by XavierPaquet-Rapold** [comment]
Doesn't seem to be a problem as of v4.21.5
