### ISSUE TITLE
Auto-merge dependabot PR.

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#431]
**Is your feature request related to a problem? Please describe.**
As a maintainer/dev of this project, I don't want to be spammed by dependabot.

**Describe the solution you'd like**
The PR created by dependabot should be automatically merged if everything is working. So when a PR is created by the bot:

- the entire CI should run but the tag validation error and the creation of a pre-release (not sure for this one, what do you think folks? 🤔) should be ignored.
- if the entire CI can run (and so all the tests for the project are passing) the PR should be automatically merged. 

**Additional context**
We could use the CI to drop the comment `@dependabot merge` (see [docs](https://docs.github.com/en/enterprise-server@3.3/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands)) or directly this [action](https://github.com/marketplace/actions/dependabot-auto-merge) which give us a little more control.

**Comment by MysticFragilist** [comment]
Penses tu qu'on serait mieux de laisser les PRs? Je pensais à ça et peut-être que ça pourrait occasionner des issues s'il n'y a personne pour faire des reviews manuels derrière. J'donne un exemple:

Dependabot bump une version d'une dépendance, exemple flutter_webview. Le build et le CI passe, tout baigne. Par contre, ça a occasionné des problèmes de display des pages web parce que la version de la dépendance a une issue.

Si on a un review manuel à faire du genre checkout la branche run l'appli pour au moins aller voir s'il y a pas des problèmes, ça pourrait éviter des erreurs qu'on aurait pas couvert dans les tests peut-être?

Parce que essentiellement quand un membre fait une PR, on lui fait confiance pour qu'il aille au moins lancé l'application dans sa branche, mais avec le bot, il fait pas ça en background.

Un exemple concret serait la PR #429 qui aurait échappé au CI.

Tu me diras ce que t'en penses! 😀

**Comment by apomalyn** [comment]
Pour la #429, en fait le CI n'a pas été exécuter parce que le changement est dans le dossier .github (exclut du CI) va falloir modifier le CI pour s'assurer que l'ensemble soit executer 😄 

Je suis d'accord avec toi, pour le moment nos tests n'assure pas une confiance absolu (malheureusement) dans le CI. C'est pas parce que le CI fonctionne que l'application fonctionne...L'idée serait d'augmenter la confiance dans les tests (en augmenter la qualité des tests, leur coverage et en ajoutant des tests d'integration et/ou e2e) et une fois que ce niveau de qualité (⚠️ ici je parle de qualité général au sens logiciel parce que l'app est vraiment de bonne qualité je trouve! Bon après je suis peut-être biaisé) sera atteint on pourra s'interesser a cette issue. Qu'en penses-tu?

**Comment by XavierPaquet-Rapold** [comment]
Not wanted, for security reasons
