### ISSUE TITLE
No schedule for new user that want to see the schedule for autumn

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#436]
**Describe the issue** 
```idk if this is normal but Im going to ets in September and I chose my schedule , but I don't see any classes when I go to the schedule tab```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-491249745.png?raw=true)

**Device Infos** 
- **Device:** IN2025 
- **Version:** 4.9.4 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1648510060 
- **Platform operating system:** android 
- **Platform operating system version:** IN2025_11_C.11

**Comment by MysticFragilist** [comment]
@apomalyn c'est "normal" comme behavior ça? Est-ce que c'est comme les notes où l'on doit attendre qu'ils soient entrer dans signets par le professeur?

**Comment by apomalyn** [comment]
Exactement, même si tu es inscrit et avec l'horaire de construit, tant que les profs et salles n'ont pas été assigné il y a pas d'horaire.
Ça pourrait être une bonne chose de mettre une page de FAQ dans l'app (ou rediriger vers la FAQ de l'école si elle existe)😀

**Comment by MysticFragilist** [comment]
> Exactement, même si tu es inscrit et avec l'horaire de construit, tant que les profs et salles n'ont pas été assigné il y a pas d'horaire. Ça pourrait être une bonne chose de mettre une page de FAQ dans l'app (ou rediriger vers la FAQ de l'école si elle existe)😀

Ahh d'accord! Super, dans ce cas là, ça pourrait être intéressant effectivement! 😄

**Comment by MysticFragilist** [comment]
FAQ done! On peut fermer ceci!
