### ISSUE TITLE
 Percentile rank don't match Signets

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#437]
**Describe the issue** 
```Tout d'abord, 99% de l'application marche A1, excellente job! Maintenant pour le bogue, j'ai remarqué que mes rangs centile sur l'appli ne concordent pas exactement avec ceux de SIGNETS. Est-ce que vous savez pourquoi? Sinon à enquêter!```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-399726290.png?raw=true)

**Device Infos** 
- **Device:** Pixel 3 
- **Version:** 4.9.4 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1648510060 
- **Platform operating system:** android 
- **Platform operating system version:** SP1A.210812.016.C1

**Comment by MysticFragilist** [comment]
Ceci m'arrive aussi! La différence est minime, mais ça pourrait créer de la confusion chez l'utilisateur. Après investigation, on obtient directement le rang centile de l'API de l'école. Je ferai un suivi auprès de Christian pour qu'il ramène le problème à l'équipe qui s'occupe de Signets API.

**Comment by MysticFragilist** [comment]
Relancer Christian le 30 mai (en congé)

**Comment by MysticFragilist** [comment]
Fixé depuis quelques temps, oublié de faire l'update ici!
