### ISSUE TITLE
Remove dependabot from contributors

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#454]
**Describe the bug**
As a user of the app, I don't want to see dependabot as a contributor.

**To Reproduce**
1. Go to More
2. Click on Contributors
4. See dependabot in the list

**Expected behavior**
Remove dependabot from the list by looping through user and removing any that are named: 'dependabot'

**Screenshots**
![image](https://user-images.githubusercontent.com/25663435/168691916-71d42752-afae-4a63-82ee-0b949974cc27.png)

**Smartphone (please complete the following information):**
 - Device: All

**Additional context**
N/A

**Comment by eneiss** [comment]
Fixed in #455

**Comment by ByUnal** [comment]
I couldn't understand how to remove depandabot from contributors ? There is no remove button for it

**Comment by DataJuggler** [comment]
> I couldn't understand how to remove depandabot from contributors ? There is no remove button for it

How do I remove it. I still see it listed?
