### ISSUE TITLE
Impossible to see the name for the evaluation with a long title  

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#471]
**Describe the issue** 
```Impossible de voir les titres au complet lorsque le nom du devoir est long. Je suggèrerais un texte défilant peut-être uniquement lorsque l'évaluation est ouverte.    -Sam```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-907802210.png?raw=true)

**Device Infos** 
- **Device:** SM-G781W 
- **Version:** 4.11.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1653640016 
- **Platform operating system:** android 
- **Platform operating system version:** SP1A.210812.016.G781WVLS6FVD2

**Comment by MysticFragilist** [comment]
En gros c'est vraiment pour les 2 avant dernières activités!

**Comment by MysticFragilist** [comment]
On pourrait utiliser ceci comme package pour scroller le text quand sélectionné:
https://pub.dev/packages/marquee
