### ISSUE TITLE
Add a button in the home page for users having difficulty logging in

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#476]
**Is your feature request related to a problem? Please describe.**
Users may encounter difficulties when logging in. 

**Describe the solution you'd like**
Add a button in the logging page with the message : 
'Need help? Contact us here" / "Vous éprouvez des problèmes ? Contactez-nous ici"

The button should redirect the user to his mailbox with the email of the club already registered.

**Comment by camillebrulotte** [comment]
@ApplETS/general Hey hey ! :D Avec @MysticFragilist nous avons eu l'idée d'ajouter un bouton sur la page d'authentification pour les personnes qui éprouvent des difficultés à se connecter. 

Certains utilisateurs laissent un commentaire dans le store puisqu'ils éprouvent des difficultés à se connecter avec leur code universel/mot de passe. Mais généralement c'est parce qu'ils avaient saisi les mauvaises informations. 🙁 

Ainsi, ils seront peut-être plus portés à nous contacter directement pour de l'aide ! Vous en pensez quoi ? :D

**Comment by JonathanDuvalV** [comment]
Ouais je penses que ca pourrait être une bonne idée!

**Comment by HugoMigner** [comment]
Oui! Ça éviterait peut-être des 1/5 stars quand les étudiants peuvent pas se connecter... 😑

**Comment by eneiss** [comment]
Bonne idée ! 💯 

Autre possibilité (peut-être à faire en plus ?), on pourrait mettre un petit hint sur le champ du code universel, je pense que je suis pas la seule à jamais savoir lequel c'est 😅 
Le hint pourrait par exemple donner le format du code quand on appuie sur le ❔, du genre AB12345 (cf le design pas très beau juste en-dessous).

C'est une solution plus légère qu'on aurait plus tendance à utiliser par réflexe quand on a un doute par rapport à une page "besoin d'aide", et ça aiderait peut-être à ce que les gens qui nous contactent pour de l'aide le fassent parce qu'ils ont un vrai problème d'authentification.

Vous en pensez quoi ?

<img src="https://user-images.githubusercontent.com/33004979/172864833-9df6904a-e07e-4c5e-8460-752c17e548c9.png" width="300">

**Comment by camillebrulotte** [comment]
> 

Bonne idée, je ferais les deux !! :D
