### ISSUE TITLE
Course acronyms move when page is clicked

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#480]
**Describe the issue** 
```Le sigle STA206 se déplace quand on clique```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-202164427.png?raw=true)

**Device Infos** 
- **Device:** SM-G970W 
- **Version:** 4.11.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1653640016 
- **Platform operating system:** android 
- **Platform operating system version:** SP1A.210812.016.G970WVLS6HVA1

**Comment by HugoMigner** [comment]
Est-ce que ça fait référence à ce qu'on avait discuté l'autre fois? Que quand on scroll le titre se "téléporte" genre? Jsuis pas trop sur de ce qu'on veut dire par "Le sigle se déplace quand on click".

![Scroll](https://user-images.githubusercontent.com/48542098/174129125-2192fb8a-f31e-48fb-a41d-870743edffa4.gif)

**Comment by MysticFragilist** [comment]
C'est ça que je me demande aussi... peut-être que vu qu'il fait juste cliquer en draggant son doigt un petit peu ça déplace le sigle? C'est le guess le plus plausible en effet! Je propose qu'on close l'issue en la linkant avec l'autre qui fait référence à ce problème.

**Comment by MysticFragilist** [comment]
Fixer la position et changer la taille pour eviter l'animation qui "saute/descend vers le bas".

**Comment by Anthony-karabian** [comment]
https://user-images.githubusercontent.com/60085081/193500662-88f1660e-c99c-403e-b96a-dea08082c085.mp4

**Comment by Anthony-karabian** [comment]
@MysticFragilist Thoughts ?

**Comment by MysticFragilist** [comment]
Noiiice j'pense que j'aime vraiment mieux comme ça que quand lle texte "jerk" vers le bas!! :D Good job! @eneiss t'en penses quoi toi?

**Comment by HugoMigner** [comment]
Ouais c'est clean!! 🔥

**Comment by eneiss** [comment]
> Noiiice j'pense que j'aime vraiment mieux comme ça que quand lle texte "jerk" vers le bas!! :D Good job! @eneiss t'en penses quoi toi?

C'est vraiment nice comme ça je trouve 💯

**Comment by Anthony-karabian** [comment]
This should be closed no, we already merged to master the changes ? @MysticFragilist
