### ISSUE TITLE
Give dependabot sufficient permissions for GitHub actions

### ISSUE THREAD

**Issue by eneiss** [ApplETS/Notre-Dame#481]
**Is your feature request related to a problem? Please describe.**

As a developer, at the moment I have to manually re-run the test phase of the CI for every automatic PR that dependabot opens.
If I understood the issue correctly, this happens because the bot can't read secrets that are needed to run this job in the CI.

![image](https://user-images.githubusercontent.com/33004979/174495319-ba0a602c-2bd2-431f-abca-9aff0e390793.png)

**Describe the solution you'd like**

I would like the bot to have sufficient permissions to run this job successfully by itself.

**Describe alternatives you've considered**

I'm not very familiar with GitHub actions but after a bit of research I think I found an explanation for this issue and a way to fix it [in this GitHub blog post](https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/).
We should be able to set permissions in the workflow to enable secrets for dependabot, **after making sure this would not create security issues**.

**Comment by eneiss** [comment]
I found this part of the GitHub docs that seems related : [link](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)

**Comment by XavierPaquet-Rapold** [comment]
Finished with #894
