### ISSUE TITLE
Error toast displayed when course grades summary empty

### ISSUE THREAD

**Issue by eneiss** [ApplETS/Notre-Dame#489]
**Describe the bug**
As a user, I find it disturbing that the app sometimes displays a pop-up for an error that actually happens when a course's grades summary is empty.

This has already happened to me a few times when professors had not uploaded the course's grade details yet, and it also happens with the special course PRJ009 ("Rédaction du projet en progression") as shown in the screenshot below.

**To Reproduce**
1. Tap on a course card to display its details (grades and stuff)
2. If the course has an empty grade summary, a toast shows up saying there's an error.

**Expected behavior**
I believe this is not a desired behavior, as it is not the result of a Signets/app service error but rather it is due to the (temporary or permanent) lack of grade details uploaded to Signets.
I think this error is misleading as it implies it might go away if you refresh the page or come back later, which is not the case.

**Screenshots**

<img src="https://user-images.githubusercontent.com/33004979/176037629-c6b91cae-4522-4f9c-9748-649e1d75d027.jpg" width=30%>

**Additional context**

I investigated the issue a bit, and it seems to be that `SignetsError.gradesEmpty` is the error thrown by the Signets API in the case of an empty grades summary, and this error is re-thrown (which triggers the in-app toast) when I think it shouldn't be.

<details>
<summary>Piece of code in course_repository.dart (l.~420) mentioned above:</summary>

```dart
    try {
      final String password = await _userRepository.getPassword();

      summary = await _signetsApiClient.getCourseSummary(
          username: _userRepository.monETSUser.universalCode,
          password: password,
          course: course);
      _logger.d("$tag - getCourseSummary: fetched ${course.acronym} summary.");
    } on Exception catch (e, stacktrace) {
      if (e is ApiException) {
        if (e.errorCode == SignetsError.gradesEmpty ||
            e.message.startsWith(SignetsError.gradesNotAvailable)) {
          _logger.e(
              "$tag - getCourseSummary: Summary is empty for ${course.acronym}.");
          rethrow;
        }
      }
      _analyticsService.logError(tag, e.toString(), e, stacktrace);
      _logger.e("$tag - getCourseSummary: Exception raised $e");
      rethrow;
    }
```

</details>

<details>
<summary>Error shown in the flutter console (for another course that had the same issue until recently): </summary>

```
I/flutter (20685): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (20685): │ #0   CourseRepository.getCourseSummary (package:notredame/core/managers/course_repository.dart:431:19)
I/flutter (20685): │ #1   <asynchronous suspension>
I/flutter (20685): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (20685): │ ⛔ CourseRepository - getCourseSummary: Summary is empty for MGL825.
I/flutter (20685): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (20685): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (20685): │ #0   CourseRepository.getCourses (package:notredame/core/managers/course_repository.dart:386:19)
I/flutter (20685): │ #1   <asynchronous suspension>
I/flutter (20685): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (20685): │ ⛔ CourseRepository - getCourses: Exception raised while trying to get summary of MGL825.
I/flutter (20685): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by XavierPaquet-Rapold** [comment]
Merged with #842
