### ISSUE TITLE
Rate us button not doing anything

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#511]
**Describe the issue** 
```The rate us button doesn't do anything.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-45804633.png?raw=true)

**Device Infos** 
- **Device:** Pixel 6 
- **Version:** 4.11.1 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1653640016 
- **Platform operating system:** android 
- **Platform operating system version:** TP1A.220624.021

**Comment by eneiss** [comment]
Fixed in #470
