### ISSUE TITLE
Error on schedule tab - schedule not displayed

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#512]
**Describe the issue** 
```Quand je vais sur horaire, un message apparaît qui dit : une erreur est survenue. Je ne peut malheureusement pas voir mon horaire depuis quelques jours ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-1062264231.png?raw=true)

**Device Infos** 
- **Device:** CLT-L04 
- **Version:** 4.11.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1653640016 
- **Platform operating system:** android 
- **Platform operating system version:** CLT-L04 10.0.0.172(C792E8R1P4)

**Comment by eneiss** [comment]
Duplicate #515
