### ISSUE TITLE
Course not appearing in schedule view

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#513]
**Describe the issue** 
```un cours n'apparaît pas dans mon calendrier celui de math350```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-273291553.png?raw=true)

**Device Infos** 
- **Device:** SM-A515W 
- **Version:** 4.11.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1653640016 
- **Platform operating system:** android 
- **Platform operating system version:** SP1A.210812.016.A515WVLU7DVD1

**Comment by XavierPaquet-Rapold** [comment]
Probably an API error, this issue is also isolated, so closing for now. Might review if another user as the same problem
