### ISSUE TITLE
An "error has occurred" on multiple devices throughout the week

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#515]
**Describe the issue** 
```“an error as occurred”```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-143110389.png?raw=true)

**Device Infos** 
- **Device:** iPhone13,4 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1645469727 
- **Platform operating system:** ios 
- **Platform operating system version:** Version 15.6.1 (Build 19G82)

**Comment by MysticFragilist** [comment]
Il semblerait que plusieurs personnes reçoivent l'erreur "An error has occurred" dans l'application quand ils naviguent entre les pages.

**Comment by JeremieBergeron** [comment]
Personnellement, je ne vois même pas mon horaire même avec le portail
![image](https://user-images.githubusercontent.com/34408507/191522404-6c19102c-4fe2-4cbc-8291-5f554d8bc57d.png)

Le problème doit venir directement de l'ets.

**Comment by camillebrulotte** [comment]
Fixed by ti <3

**Comment by eneiss** [comment]
Yessssssssssssssssssssssssssssssssssssssssssssss 🔥 
Thanks TI service 💯
