### ISSUE TITLE
Fastlane Android release no longer working - Play Store missing information

### ISSUE THREAD

**Issue by eneiss** [ApplETS/Notre-Dame#518]
**Describe the bug**
Releasing new versions of the app on the Play Store is no longer possible because of missing app information.

**To Reproduce**
1. Run the fastlane release workflow
2. The following error occurs in the "Deploy to store" job : `[20:24:21]: Google Api Error: Invalid request - This app has no data safety declaration.`

**Expected behavior**
The workflow should succeed and the app should be released to the Google Play Store automatically.

**Additional context**
It seems that the app's Play Store page is missing data safety information, and this is preventing us from releasing any new version since July:

> By July 20, 2022, all developers must declare how they collect and handle user data for the apps they publish on Google Play, and provide details about how they protect this data through security practices like encryption. 
([Source](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en))

This could be fixed by adding the missing information using the Play Console.

**Comment by MysticFragilist** [comment]
régler!
