### ISSUE TITLE
Broadcast important information using Firebase Remote Config

### ISSUE THREAD

**Issue by AntoineLemelin** [ApplETS/Notre-Dame#528]
**Is your feature request related to a problem? Please describe.**
En tant que membre d'App|ETS je veux être en mesures de diffuser un message à l'ensemble des utilisateurs grâce à un remote config

**Describe the solution you'd like**
Mettre une bannière dans le dashboard qui va fetch une remote config si le texte est null elle ne l'affiche pas si le texte n'est pas null elle l'affiche. Ne pas oublier de traduire anglais français 

**Describe alternatives you've considered**
A discuté.

**Additional context**
Lors d'un problème nous pourrons rapidement atteindre nos clients grâce a cette bannière.

**Comment by apomalyn** [comment]
Le projet What's New est directement relié a cela 😄 A voir avec @MysticFragilist où le dev en est 😄 
En soit What's New est meme plus grand que cela puisque cela permettrait a l'ecole et aux autres clubs de potentiellement mettre des messages.

**Comment by eneiss** [comment]
> Le projet What's New est directement relié a cela 😄 

C'est vrai, dans l'idéal on aurait pas besoin de cette feature, mais je pense qu'en attendant what's new ça serait vraiment pratique (cf toutes les issues qu'on reçoit ces derniers jours à cause d'un problème de schedule pas affiché 😅 ).
Ça doit pas être trop compliqué à implémenter et ça permettrait aux gens de pas rester dans le flou sur les problèmes de l'app

**Comment by MysticFragilist** [comment]
Je propose sinon, comme l'issue problématique est maintenant close et qu'on a plus de temps, de setup des notifications depuis notre projets firebase pour ce genre d'avertissement. En plus, si on a déjà les notifs de fonctionnel, on pourra utiliser cela comme levier pour aller chercher les notifs dans Signets. Avec ce tutoriel ça ne semble pas trop complexe à implémenter sur flutter en passant par firebase: https://firebase.flutter.dev/docs/messaging/notifications/ .

**Comment by MysticFragilist** [comment]
> Je propose sinon, comme l'issue problématique est maintenant close et qu'on a plus de temps, de setup des notifications depuis notre projets firebase pour ce genre d'avertissement. En plus, si on a déjà les notifs de fonctionnel, on pourra utiliser cela comme levier pour aller chercher les notifs dans Signets. Avec ce tutoriel ça ne semble pas trop complexe à implémenter sur flutter en passant par firebase: https://firebase.flutter.dev/docs/messaging/notifications/ .

Je retire mon message, je vais créer une issue à côté pour ce que j'ai mentionné 😄
