### ISSUE TITLE
"Une erreur est survenue" and no page loading (?)

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#545]
**Describe the issue** 
```« une erreur est survenue » apparaît toujours en bas de l’écran et aucune page ne charge```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-1023973133.png?raw=true)

**Device Infos** 
- **Device:** iPhone12,1 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1645469727 
- **Platform operating system:** ios 
- **Platform operating system version:** Version 14.3 (Build 18C66)

**Comment by eneiss** [comment]
Duplicate #515 ?

**Comment by MysticFragilist** [comment]
J'pense que oui on pourra la fermer selon moi, j'sais pas à votre avis?

**Comment by eneiss** [comment]
> J'pense que oui on pourra la fermer selon moi, j'sais pas à votre avis?

Sûrement ouais

**Comment by MysticFragilist** [comment]
duplicate of #515
