### ISSUE TITLE
Improve schedule layout

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#607]
**Describe the issue** 
```La disposition de l'horaire est bizarre et peu visuelle. Ca prendrait des blocs qui montre les activités comme dans toutes les applications avec un horaire avec l'heure comme axe vertical. Une liste c'est très peu utile, même cheminot fait mieux. Pourquoi avoir régressé?```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-675811750.png?raw=true)

**Device Infos** 
- **Device:** SM-F926B 
- **Version:** 4.12.7 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1662053189 
- **Platform operating system:** android 
- **Platform operating system version:** SP2A.220305.013.F926BXXU1CVHB

**Comment by MysticFragilist** [comment]
Est-ce qu'on close celle-là en faveur de la #611 ?
