### ISSUE TITLE
Theme in settings does not work well

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#61]
**Describe the bug**
The theme does not stay when destroying the app process.

**To Reproduce**
1. Go to More
2. Go to Settings
3. Click on Theme
4. Select Dark (if the default theme of the phone is light) _or_ Select Light (if the default theme of the phone is dark)
5. Quit the app
6. Launch the app
7. Go to More
8. Go to Settings

**Expected behavior**
The app should keep the theme color of the theme selected in Settings.

**Screenshots**

https://user-images.githubusercontent.com/37625944/110405935-65957f00-804f-11eb-935e-d09636ee4810.mp4

**Comment by apomalyn** [comment]
Good catch @camillebrulotte !

**Comment by AlexandreMarkus** [comment]
I think this happens because the SharedPreferences are not loaded yet. If we hot reload right after restarting the app, it does apply the theme and language
