### ISSUE TITLE
Add Calendar View to Schedule Tab

### ISSUE THREAD

**Issue by HugoMigner** [ApplETS/Notre-Dame#611]
**Is your feature request related to a problem? Please describe.**
We've had multiple requests for a revamp of the "Schedule Tab". This issue will serve as an experimentation/possible implementation of calendar-view.

**Describe the solution you'd like**
A toggle in the settings would allow the user to switch between the current Schedule view and a Calendar view. Eventually, the calendar view would potentially overtake the previous one.

**Describe alternatives you've considered**
N/A

**Additional context**
[calendar-view](https://pub.dev/packages/calendar_view) on pub.dev

**Comment by eneiss** [comment]
Great! We could consider #607 closed when this issue is resolved since it's the same idea behind
