### ISSUE TITLE
Color code for classes

### ISSUE THREAD

**Issue by MarcOlivier-Methe** [ApplETS/Notre-Dame#64]
It would be nice if all the classes where color coded like in the previous version. For example, PHY335 could be green, COM110 could be yellow, etc... 

This feature would be especially useful with the schedule feature of the application.

**Comment by zaclimon** [comment]
Hey! First of all thanks for creating the first user issue on the project, it's really appreciated! 🎉 We'll consider your suggestion and see if it'll be integrated.

Do note that we will stop our activities next week (Mar. 25th) in preparation for the finals so don't be surprised if we don't reply in the next days/weeks.

**Comment by Sonphil** [comment]
Implemented in #174

Each course now has a specific color in the schedule.
![image](https://user-images.githubusercontent.com/22182973/62879919-292a6180-bcfa-11e9-91fe-459b117a6f0f.png)
