### ISSUE TITLE
Control Language setting + ability to see a calendar in schedule 

### ISSUE THREAD

**Issue by misterjello** [ApplETS/Notre-Dame#65]
Hey guys first I would like to start by saying the app look amazing and you guys did a great job !!!
I currently have my phone setting in English  but I would like to have the ability to change the language only for this app and change it in French instead. 
+ I can't find a calendar like the one we had in the previous version.

**Comment by zaclimon** [comment]
Hey, thanks for the support! :slightly_smiling_face:  We'll look over what we can do for changing the language in the app.

As far as the calendar is concerned, we decided that it would be better for us to only keep the list layout. Was that what you were referring to? (We're currently working on implementing future weeks as well. Check #56 for more details)

**Comment by Sonphil** [comment]
I created an issue (#192) for the language setting.
