### ISSUE TITLE
When clicking multiple times on the submit bug report, it creates multiple issue

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#663]
**Describe the bug**
As a user that wants to create a bug report, if I click multiple times on submit there is multiple bug report that get sent out to github.

**To Reproduce**
1. Go to bug report view
2. Click on submit x3 before the page closes

**Expected behavior**
The button should be disabled once the button is clicked one time

**Screenshots**
N/A

**Smartphone (please complete the following information):**
All

**Additional context**
N/A

**Comment by Anthony-karabian** [comment]
J'ai fix le bug de mon coté

**Comment by Anthony-karabian** [comment]
@MysticFragilist hasn't this already been merged ? Should we close this issue then ?

**Comment by XavierPaquet-Rapold** [comment]
Finished with #673
