### ISSUE TITLE
Email seems to not open

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#672]
**Describe the issue** 
```courriel ouvre pas ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-704365641.png?raw=true)

**Device Infos** 
- **Device:** iPhone11,8 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1645469727 
- **Platform operating system:** ios 
- **Platform operating system version:** Version 16.0.2 (Build 20A380)

**Comment by XavierPaquet-Rapold** [comment]
@MysticFragilist is it asking to integrate emails into the app ? If it is, we might want to close as not in scope

**Comment by EffBureau** [comment]
Pas assez d'information. L'issue est trop vieille pour faire un suivi.
