### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#68]
**Is your feature request related to a problem? Please describe.**
To improve the user experience, we should migrate the application to null safety which is available since Dart 2.12.0.

**Additional context**
[Dart migration guide to null safety](https://dart.dev/null-safety/migration-guide)

**Comment by MysticFragilist** [comment]
https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md

**Comment by MysticFragilist** [comment]
Also, it would be necessary to start by migrating the https://github.com/ApplETS/ETS-API-Clients project first, since it's a dependency of Notre-Dame.

**Comment by JonathanDuvalV** [comment]
> Also, it would be necessary to start by migrating the https://github.com/ApplETS/ETS-API-Clients project first, since it's a dependency of Notre-Dame.

@MysticFragilist ETS-API-Clients seems to already have been migrated to null safety https://github.com/ApplETS/ETS-API-Clients/commit/509494d5805bf324a28da7ec2483df34e20d4031

**Comment by JonathanDuvalV** [comment]
There's a command to check if all dependencies have been migrated to null-safety and everything seems fine on Notre-Dame

<img width="696" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/45638733/041632d8-a349-4e89-ba21-2be32d7ea971">

I'll start to look into migrating to null-safety for notre-dame
