### ISSUE TITLE
CI jobs not running after github-actions bot commits

### ISSUE THREAD

**Issue by eneiss** [ApplETS/Notre-Dame#681]
**Describe the bug**
CI job don't run after the bump-version bot from github actions pushes commits.

**To Reproduce**
1. Create a pull request
2. Add a version label
3. Wait for the github action bot to push its commit
4. See that no CI jobs have been run after this commit

**Expected behavior**
CI jobs should run even after the github action bot pushes its commit. **This is critical** because if a developer adds a version label to their PR, they can no longer see if the CI jobs (tests and such) would have succeeded. This makes it possible to merge changes into master _without running checks at all_.

**Screenshots**
Example on PR #677: no CI/CD jobs have been run after the github-actions bot pushed its commit:
![image](https://user-images.githubusercontent.com/33004979/194777008-f1ad45d6-1e6b-4149-a15a-59e5f0d792ed.png)

**Additional context**
I haven't investigated the issue yet but I hope the problem comes from some initial filtering of github action triggers that prevents CI jobs to run after bot commits (otherwise the issue might be annoying to fix).

**Comment by XavierPaquet-Rapold** [comment]
Will be fixed with #699
