### ISSUE TITLE
[More] Logout on iOS seems to fail the cache deletion

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#69]
@apomalyn 

When i logout on IOS, it shows :
```
2021-03-20 11:46:36.079522-0400 Runner[67998:1743837] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/Users/camillebrulotte/Library/Developer/CoreSimulator/Devices/3370171F-E666-4866-9952-51694FB5B0B8/data/Containers/Data/Application/85C98B63-BC5E-4EF0-A3EE-5ED69745E0F9/Library/Caches/ETSMobileCache/f075f330-8774-11eb-b768-05ecdca60c31.file' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#8      _rootRun (dart:async/zone.dart:1354:13)
#9      _CustomZone.run (dart:async/zone.dart:1258:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Or else, everything seems to work the same way as on Android.

_Originally posted by @camillebrulotte in https://github.com/ApplETS/Notre-Dame/issues/64#issuecomment-803388875_

By the very nature of the application, this is not a blocking issue but we should investigate and fix this.

**Comment by camillebrulotte** [comment]
@apomalyn @AlexandreMarkus Hello ! :D Comment est-ce qu'on reproduisait le bogue déjà ? Je me déconnecte mais j'ai plus l'erreur ...

**Comment by AlexandreMarkus** [comment]
@camillebrulotte Il se pourrait que le bug soit réglé suite a une mise a jour du plugin. Le bug se produisait lors du logout sur IOS seulement (message d'erreur dans la console)

**Comment by camillebrulotte** [comment]
Donc, je crois qu'il n'est plus là. Si je me souviens bien, je ne faisais que me déconnecter (sur IOS), mais il ne semble plus apparaître. 🤷‍♀️

**Comment by AlexandreMarkus** [comment]
> Donc, je crois qu'il n'est plus là. Si je me souviens bien, je ne faisais que me déconnecter (sur IOS), mais il ne semble plus apparaître. 🤷‍♀️

Super!! Si tu te connectes a nouveau, la cache semble être vide?

**Comment by AlexandreMarkus** [comment]
Si @apomalyn n'a plus cette erreur lui aussi, on pourrait close cette issue

**Comment by apomalyn** [comment]
Je n'ai pas eu l'erreur! :D Closes this issues 😄
