### ISSUE TITLE
Fix golden tests

### ISSUE THREAD

**Issue by XavierPaquet-Rapold** [ApplETS/Notre-Dame#693]
**Is your feature request related to a problem? Please describe.**
As a developer, it's difficult to work with golden tests. The tests fail on platforms other than Linux. Also, the golden file update is difficult to do on the CI.

**Describe the solution you'd like**
- [ ] Remove the `[CI UPDATE GOLDENS]` check from the ci main_workflow.yaml file (always update the golden files).
- [ ] Update the golden tests to skip them on platforms other than Linux. [(skip golden tests depending on platform)](https://blog.codemagic.io/flutter-golden-tests-with-codemagic-cicd/)
- [ ] Add check in pull_request_template file asking to verify if golden files changes were verified and accepted.

**Describe alternatives you've considered**
This issue is an alternative solution for #691 

**Additional context**
This solution will fix the tests failing on platforms other than Linux, the golden file update problem and the updates that could make the CI fail.
The new flow of development would be:
1. Create a PR;
2. The CI executes automatically;
3. The golden files update automatically in a new commit;
4. All checks are successful;
5. During the review, see if the changes to the goldens are consistent with the objective of the PR.

**Comment by MysticFragilist** [comment]
Je rajouterais qu'il faudrait updater le fichier pull_request_template pour demander de s'assurer que les fichiers goldens ont été regardé et accepté. (un check de plus dans la liste)
