### ISSUE TITLE
Missing refresh text in course details

### ISSUE THREAD

**Issue by XavierPaquet-Rapold** [ApplETS/Notre-Dame#712]
**Describe the bug**
Since the material 3 support was released, on the course details without grades, the "refresh" text of the refresh button is missing.

**To Reproduce**
1. Go to the student page.
2. Click on a course without grades (courses from the next session)
3. See a red button without text below the "Aucune note disponible" text.

**Expected behavior**
The button should contain the "Refresh" or "Rafraichir" text.

**Screenshots**
![image](https://user-images.githubusercontent.com/80051842/200900694-b38921da-9f8b-44c4-a86f-1e81277675b2.png)

**Comment by J01716** [comment]
After investigation, the buttons still contains the text it is supposed to, only the color is the same as the button's color.
Notre_Dame\lib\ui\widgets\grade_not_available.dart in the ElevatedButton (currently lines 41-47)
