### ISSUE TITLE
CI doesn't retrigger when github bot commit

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#764]
**Describe the bug**
When I'm in a PR, the bot must retrigger the CI.

**To Reproduce**
1. Create a PR
2. Add one of the version tag
3. See error

**Expected behavior**
Retrigger the CI.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by XavierPaquet-Rapold** [comment]
@MysticFragilist  According to [this page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks), a required status check should prevent this issue by blocking the merge with the "some checks haven't completed yet" message.

I don't know how the checks are set, but I would recommend checking if the `dev-workflow` is a required check.
