### ISSUE TITLE
Can't report a bug on IOS

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#797]
**Describe the bug**
Can't report a bug on a IOS device.

**To Reproduce**
Steps to reproduce the behavior (on IOS):
1. Go to More
2. Click on Report a bug
3. Report a bug and send it
4. No issue is created on Github

**Expected behavior**
An issue should be create on Github

**Comment by camillebrulotte** [comment]
A très probablement brisé après une des deux PR : https://github.com/ApplETS/Notre-Dame/pull/708 ou https://github.com/ApplETS/Notre-Dame/pull/703

**Comment by camillebrulotte** [comment]
@Pascal1132 Aurais-tu une idée ? :o

**Comment by Pascal1132** [comment]
Mmmm étrange! Aucune idée.. 🙃

**Comment by MysticFragilist** [comment]
Est-ce que ce bug est toujours présent?

**Comment by XavierPaquet-Rapold** [comment]
@camillebrulotte Est-ce que ce bug est toujours présent?

**Comment by camillebrulotte** [comment]
Normalement oui!

**Comment by XavierPaquet-Rapold** [comment]
Removed with #1099
