### ISSUE TITLE
Quick link and security

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#8]
**Is your feature request related to a problem? Please describe.**
As a student, I want to find in the application all the procedures in case of emergency and all the useful link of the ETS (MonÉTS, Bibliotech, News, Moodle, Heuristique, AEETS, ...)

**Comment by AlexandreMarkus** [comment]
![image](https://user-images.githubusercontent.com/59664238/90430744-fc8bf100-e095-11ea-84cc-53cc11687e1d.png)

**Comment by apomalyn** [comment]
@AlexandreMarkus bon boulot!
Quelques petits commentaires/questions sur le visuel en attendant d'avoir la PR:
1. le padding des cartes est probablement trop faible (on soit que le logo de la sécurité, MonETS et Heuristique sont très très proches des bordures, mais aussi les textes qui sont vraiment proches de la bordures de la cartes)
2. Il manque le "É" de ÉTS, est-ce que tu as utiliser le l10n?
3. Est-ce que tu prends en compte/a fait des tests sur le thème sombre?

**Comment by apomalyn** [comment]
Also si tu peux lui faire son projet associé histoire qu'on sache où tu en es! 😄  Merci

**Comment by AlexandreMarkus** [comment]
> Also si tu peux lui faire son projet associé histoire qu'on sache où tu en es! 😄  Merci

Parfait je vais le faire

**Comment by AlexandreMarkus** [comment]
> @AlexandreMarkus bon boulot!
> Quelques petits commentaires/questions sur le visuel en attendant d'avoir la PR:
> 1. le padding des cartes est probablement trop faible (on soit que le logo de la sécurité, MonETS et Heuristique sont très très proches des bordures, mais aussi les textes qui sont vraiment proches de la bordures de la cartes)
> 2. Il manque le "É" de ÉTS, est-ce que tu as utiliser le l10n?
> 3. Est-ce que tu prends en compte/a fait des tests sur le thème sombre?

Je vais faire 3 issues pour modifier le tout.

@apomalyn est-ce que le thème sombre est déjà implémenté pour le projet ou bien je dois le faire?

**Comment by apomalyn** [comment]
> > @AlexandreMarkus bon boulot!
> > Quelques petits commentaires/questions sur le visuel en attendant d'avoir la PR:
> > 
> > 1. le padding des cartes est probablement trop faible (on soit que le logo de la sécurité, MonETS et Heuristique sont très très proches des bordures, mais aussi les textes qui sont vraiment proches de la bordures de la cartes)
> > 2. Il manque le "É" de ÉTS, est-ce que tu as utiliser le l10n?
> > 3. Est-ce que tu prends en compte/a fait des tests sur le thème sombre?
> 
> Je vais faire 3 issues pour modifier le tout.
> 
> @apomalyn est-ce que le thème sombre est déjà implémenté pour le projet ou bien je dois le faire?

Oui il est déjà implémenter mais n'a pas encore le switch dans l'application, actuellement il suit le thème du système ^^

**Comment by AlexandreMarkus** [comment]
![Peek 2020-09-09 13-41](https://user-images.githubusercontent.com/59664238/92634459-5735f880-f2a2-11ea-8880-9cdd59284716.gif)
