### ISSUE TITLE
Reorderable links in Quicklinks

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#820]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a reorderable quicklinks page so all links can be reorder, remove or added. For this to work, we would need to maintain 1 list of all links (never changes) and one list of currently displayed links (part of the complete list). An index of each link must be saved to be able to track where the item is located.

We would also need to save theses infos in localstorage.

**Acceptance criteria**
- [ ] On page open, order the list based on the order saved;
- [ ] On long press of a quicklink, activate the reactivate feature and show small 'x' to delete a link;
- [ ] Add a way to create a link that is disappear (can't create 2 identical links too);
- [ ] On a press anywhere else without links, we should save once again the quicklinks with the order in localstorage;
- [ ] Make sure to have an initializer to insert default layout when none is found;
- [ ] Tests 🧪  

**Describe alternatives you've considered**
N/A

**Additional context**
This package could be easily used 😄 https://pub.dev/packages/reorderable_grid_view

Also, it's to note that with the new horairÉTS link, this feature is more urgent now since we don't necessarily want to schedule genrator at the same time.

**Comment by MysticFragilist** [comment]
@AntoineLemelin mention to not forget that logout should remove the cache for this ^

**Comment by JonathanDuvalV** [comment]
@ApplETS/general 

I was thinking of two different ways to add back deleted quicklinks, which one do you prefer?

Option 1: 
Second grid view that appears at the bottom when in edit mode after a long press
https://github.com/ApplETS/Notre-Dame/assets/45638733/c248c0e2-81c8-4908-8763-7f2f381ba11a

Option 2:
Modal opened from appbar (The UI of the modal isn't final)
https://github.com/ApplETS/Notre-Dame/assets/45638733/7921bace-fadb-4509-9092-5887030a2f5b

**Comment by MysticFragilist** [comment]
Hmmm... tu pourras en parler demain au meeting si tu veux! on verra ce que les gens préfère. perso j'ai pas vraiment de préférences, mais je vais y penser!

**Comment by JonathanDuvalV** [comment]
Ouais bonne idée j'en parlerai demain!
