### ISSUE TITLE
Update profil page UI

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#825]
**Describe the solution you'd like**
Change the layout of the profil page and add a progress bar for the program completion.

**Prototype**

<img width="736" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/37625944/c2669a39-3bd1-4715-aec7-6de609b160ff">

**Comment by camillebrulotte** [comment]
@ApplETS/general Hésitez pas à ajouter vos commentaires / suggestions !!

**Comment by JonathanDuvalV** [comment]
I think it would be better if the balance was red instead of green since it means you still need to pay for the session

![image](https://github.com/ApplETS/Notre-Dame/assets/45638733/50e56de0-1ce5-4d5d-b02e-0d4f74e5a862)

**Comment by camillebrulotte** [comment]
Bonne idée ! 

<img width="784" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/37625944/df28a0ca-5225-4cf0-81ff-9d2612f567a6">

**Comment by eneiss** [comment]
This looks so cool 🔥 
I think the headers of the foldable sections don't stand out enough compared to the content of these sections, maybe add a background color behind the header text or change some property of the font (bold/size?) so the two can be differentiated more easily?

**Comment by camillebrulotte** [comment]
@eneiss Sam a proposé quelque chose comme ça pour démarquer les différents programmes ! tu en penses quoi ? :D J'aime bien ! Étant donné que c'est surtout le premier (Ton bac/maitrise etc) que les gens veulent voir le plus. Les autres ont en a pas vrm besoin et avec un title comme ça ça fait un peu comme une liste. 

<img width="282" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/37625944/27d33181-98f2-4797-8859-aa63926c93dc">

**Comment by AntoineLemelin** [comment]
Just to be peaky, maybe add a "%" symbol after the number 88.0 in the circle.

**Comment by apomalyn** [comment]
Vraiment super la nouvelle page!
J'aurais un petit commentaire de style pour la carte du code permanent/code universel, les codes devraient être centré pour s'aligner avec les deux autres cartes 😄 

![image](https://github.com/ApplETS/Notre-Dame/assets/22211097/79297540-a153-4830-b74f-76a5f624870f)

**Comment by camillebrulotte** [comment]
Sure ! :D (C'est flou à cause de mes écrans)
<img width="155" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/37625944/d1e3781a-5375-4caf-bc7b-e9df22fd7ad0">

**Comment by camillebrulotte** [comment]
Sure ! :D (C'est flou à cause de mes écrans)
<img width="151" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/37625944/fad343c5-28e1-4ac1-9272-a1d70f1ff44f">
