### ISSUE TITLE
[MORE] first time opening the about page, the animation makes a weird move

### ISSUE THREAD

**Issue by AlexandreMarkus** [ApplETS/Notre-Dame#85]
**Describe the bug**
first time opening the about page, the animation makes a weird move. The logo animation seems to shrink instead of growing.

**To Reproduce**
1. Go to More
2. Click on About
3. Press Back
4. Click on About again
5. See the difference between the 2 animations

**Comment by AlexandreMarkus** [comment]
take a look at this https://flutter.dev/docs/perf/rendering/shader

**Comment by AlexandreMarkus** [comment]
> take a look at this https://flutter.dev/docs/perf/rendering/shader

@apomalyn  I did test it and it doesn't seems to change anything. Will need to investigate more

**Comment by MysticFragilist** [comment]
Did you test it by building a fresh APK? On my side I manage to fix the janking when building an apk with this method (unfortunately not when launching from a dev environment tho), I pushed it on the branch feature/table_calendar_starting_day branch if you want to try it out (I also updated the wiki for building it in case). Perhaps, depending on the phone the optimization is different, it says in the article that it probably won't affect the last IOS version. Maybe it's the same with some android API version?

**Comment by AlexandreMarkus** [comment]
> Did you test it by building a fresh APK? On my side I manage to fix the janking when building an apk with this method (unfortunately not when launching from a dev environment tho), I pushed it on the branch feature/table_calendar_starting_day branch if you want to try it out (I also updated the wiki for building it in case). Perhaps, depending on the phone the optimization is different, it says in the article that it probably won't affect the last IOS version. Maybe it's the same with some android API version?
> 
> I tested it on 2 phones:
> - Google Pixel 2 API 30 Emulator
> - Samsung Galaxy S10e 

Ohh nice!! I might have done something wrong... Can you send me your APK via teams so I can see if my device is the problem
