### ISSUE TITLE
Classify imports automatically

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#855]
**Is your feature request related to a problem? Please describe.**
We sometimes forget to reorder the imports.

**Describe the solution you'd like**
I want the imports to be automatically sorted when i make a Pull request.

**Additional context**
Package found : https://github.com/fluttercommunity/import_sorter
If there is a better package to sort the imports, feel free to say !

**Comment by XavierPaquet-Rapold** [comment]
Fixed with #860
