### ISSUE TITLE
Create a dev container to be able to work on the application easily anywhere where on any machine.

### ISSUE THREAD

**Issue by mataai** [ApplETS/Notre-Dame#857]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Getting the app development workspace ready is really hard because of the old versions of flutter and java the app runs on, making a devcontainer would allow us to have a generic environment on which everything works out of the box.

**Comment by Amr-Elgazar** [comment]
Kindly elucidate any challenges or issues you may be encountering, as I am here to offer my assistance and support.

**Comment by mataai** [comment]
> Kindly elucidate any challenges or issues you may be encountering, as I am here to offer my assistance and support.
> 

@Amr-Elgazar thanks!
Last night we tried setting it up on someone's mac and the flutter installation failed in the container. I have to find some time to undust my MacBook to check out what the problem is. If you have one on hand it might take you less time than me to check it out.

**Comment by MysticFragilist** [comment]
@mataai this is close right?

**Comment by mataai** [comment]
> @mataai this is close right?

Yes

**Comment by MysticFragilist** [comment]
aight niice!

**Comment by MysticFragilist** [comment]
> > @mataai this is close right?
> 
> Yes

Si jamais t'es down tu peux faire une petite démo prochaine coding or in this case au workshop!
