### ISSUE TITLE
Add Privacy Policy webview in ETSMobile

### ISSUE THREAD

**Issue by HugoMigner** [ApplETS/Notre-Dame#858]
**Is your feature request related to a problem? Please describe.**
ETSMobile needs to have a privacy policy available to the user. We are currently experiencing issues releasing ETSMobile because of this.

**Describe the solution you'd like**
Add a webview redirecting the user to the privacy policy.

_**Possible implementation**_

- Add a button that opens a webview in the "More" section of ETSMobile.
- The webview needs to redirect the user to a URL saved in Remote Config.
- This will allow the URL to be changed easily, if necessary, and allow development of this issue before the App|ETS team receives the link to the privacy policy.

**Describe alternatives you've considered**
_To be discussed_

**Additional context**
The App|ETS team hasn't received the link to the privacy policy yet, so development of this issue is blocked. If the maintained solution is to fetch the webview link from Remote Config, development is open.

**Comment by XavierPaquet-Rapold** [comment]
Latest ETA for the privacy policy is end October
