### ISSUE TITLE
SignETS API may not be accessible on the school wifi   

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#861]
**Describe the issue** 
```incapable de ne connecter sur le wifi de l'école, mais sur mon LTE ça fonctionne ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-94332635.png?raw=true)

**Device Infos** 
- **Device:** Pixel 6a 
- **Version:** 4.21.5 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1679695472 
- **Platform operating system:** android 
- **Platform operating system version:** TQ3A.230901.001 
- **Email:** mathieu.robitaille.7@ens.etsmtl.ca

**Comment by XavierPaquet-Rapold** [comment]
L'API signÉTS n'est pas accessible sur le wifi Éduroam. Il est seulement disponible sur ETS-Campus

**Comment by EffBureau** [comment]
@XavierPaquet-Rapold C'est l'API qui bloque les requetes de ce réseau là ou le réseau qui a blacklist l'API?

**Comment by MysticFragilist** [comment]
Quelqu'un peut s'occuper de contacter [mathieu.robitaille.7@ens.etsmtl.ca](mailto:mathieu.robitaille.7@ens.etsmtl.ca) @ApplETS/general? pour savoir sur quel réseau il était et assurer un suivi savoir si ça ne fonctionne toujours pas? Je peux le faire sinon si personne ne se propose! Si tout est beau on peut fermer l'issue après!

**Comment by EffBureau** [comment]
@MysticFragilist jpeux m'en occuper

**Comment by EffBureau** [comment]
E-mail envoyé. 

j'ai oublié de te mettre en cc mais je forwarderai la reponse a qui de droit.

**Comment by MysticFragilist** [comment]
> E-mail envoyé. 
> 
> j'ai oublié de te mettre en cc mais je forwarderai la reponse a qui de droit. 

Coool! Merci Francis 😄 tu peux forward à applets@etsmtl.ca

**Comment by EffBureau** [comment]
Je copie la réponse de Mathieu ici :

"Salut Francis,

Non j'étais sur ets-invite et j'avais un problème de connexion avec ce wifi, de là la raison du bug. 

J'ai contacté GUS pour me connecter sur ets-campus et maintenant tout fonctionne normalement.

Merci pour le suivi.
Bonne journée,
Mathieu Robitaille "

**Comment by XavierPaquet-Rapold** [comment]
Merci @EffBureau d'avoir fait le suivi.

Je ferme cette issue, puisque le réseau ÉTS Invité ne devrait pas avoir accès aux API SignÉTS et MonÉTS
