### ISSUE TITLE
Course can't be seen once student became employee (probably from [SIGNETS])

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#864]
**Describe the issue** 
```Bonjour.  J'ai un problème avec l'application mobile ÉTS.  j'ai fusionné mon compte étudiant avec celui d'employé. du coup j'ai perdu accès à mes cours. Merci de m'expliquer s'il vous plaît ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-276447890.png?raw=true)

**Device Infos** 
- **Device:** SM-M336BU 
- **Version:** 4.21.5 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1679695472 
- **Platform operating system:** android 
- **Platform operating system version:** TP1A.220624.014.M336BUXXU4CWD3 
- **Email:** abbou.chafiaa@gmail.com

**Comment by EffBureau** [comment]
Email envoyé

**Comment by EffBureau** [comment]
Aucune réponse. Je ferme l'issue.
