### ISSUE TITLE
L'horaire disparait quand on sélectionne aujourd'hui.

### ISSUE THREAD

**Issue by patates-cipsi418** [ApplETS/Notre-Dame#865]
<img src="https://github.com/ApplETS/Notre-Dame/assets/81366683/fb862119-dbae-45df-a350-9cd150654e9a" width="200">

<img src="https://github.com/ApplETS/Notre-Dame/assets/81366683/dc542c6c-bab5-4270-ad77-cfaf97561e76" width="200">

<img src="https://github.com/ApplETS/Notre-Dame/assets/81366683/8bda6822-d872-4ea4-8831-8fcf5403eccd" width="200">

Pour reproduire le bug, il faut sélectionner préalablement une journée en fin de semaine comme début de semaine. Ensuite, désactivez la liste défilante.

Cela fonctionne correctement si Lundi est sélectionné.

Galaxy S10+
Android 12

**Comment by MysticFragilist** [comment]
Merci d'avoir rapporter le bogue @patates-cipsi418! Si je comprends bien, le bogue n'est présent que lorsque l'on clique sur 'aujourd'hui' un dimanche? est-ce que tu aurais remarqué qu'est-ce qu'il arrive en cas d'un samedi? 😄

**Comment by MysticFragilist** [comment]
Pourrait être related à https://github.com/ApplETS/Notre-Dame/pull/788 @HugoMigner est-ce que ça avait été fix ça? Je ne suis pas capable de reproduire sur mon téléphone

**Comment by patates-cipsi418** [comment]
Bien sûr @MysticFragilist , la version est 4.21.5,
J'ai rencontré le bug aujourd'hui, donc je n'ai pas encore fait le test samedi. 
Je fessais référence au paramètre "Premier jour de la semaine", disponible quand "Liste défilante" est active/true.

J'aimerais avoir le samedi comme début de semaine pour pouvoir mon horaire de la semaine prochaine par défaut en fin de semaine.
