### ISSUE TITLE
Intitulé de début de semaine ne correspondent pas avec les horaires affichés

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#87]
**What happened:**
```
Intitulé de début de semaine ne correspondent pas avec les horaires affichés
```

**Version:** 3.0.0-beta (30733)

**Operating system:** Android 8.1.0

**Model:** HMD Global TA-1053

**Memory:** 67% (1.2 GB used out of 1.78 GB)

**Capacity:** 91% (7.98 GB used out of 8.78 GB)

**Locale:** France French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/10/awesome_logs) 

**Attachments:** 

![screenshot_1554897015158.png](http://buglife.s3.amazonaws.com/report_attachments/a30b1f03a7df3e2d7d526f8a849b189122a7b6d8/original/screenshot_1554897015158.png?1554897268)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/10

Reported via Buglife

**Comment by Sonphil** [comment]
Fixed in #174
