### ISSUE TITLE
Add instagram to our card in the dashboard page

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#870]
**Describe the solution you'd like**
Since we  now have an instagram (https://www.instagram.com/clubapplets/) page we should add it to the card in the dashboard page : 
<img src="https://github.com/ApplETS/Notre-Dame/assets/37625944/f396306d-0881-4d43-93d4-db744585aa53" alt="Girl in a jacket" width="250">

**Comment by JanaganSaravanan** [comment]
Hi! It looks interesting. Can i work on this issue? and please give me some head start.
