### ISSUE TITLE
En mode paysage, l'affichage de l'horaire sur un petit écran dépasse en largeur la taille maximum et s'affiche par-dessus les heures à gauche.

### ISSUE THREAD

**Issue by LouisPhilippeHeon** [ApplETS/Notre-Dame#874]
Testé sur un iPhone 13 pro, iOS 17.0.3
![80C6C165-2989-4D91-BDBE-F9E78646F9E2_1_201_a](https://github.com/ApplETS/Notre-Dame/assets/83369199/c717b262-efc7-4b22-be75-4c1f44866d5c)
Aussi, normalement mon horaire affiche le samedi, mais lorsque je suis en mode paysage, le samedi n'apparaît pas dans la liste de jour en haut de l'horaire.
Le problème ne semble toutefois pas à priori relié au fait que mon horaire affiche aussi le samedi, car même si aucun jour de la fin de semaine n'est affiché, il y a un overflow à gauche.
Aussi testé sur un grand écran (iPad) et le problème n'est pas présent.

**Comment by MysticFragilist** [comment]
je pense que ton samedi est affiché à la fin puisqu'il y a 6 jours visible avec celui en overflow, as-tu PRE011 le samedi par hasard?

**Comment by LouisPhilippeHeon** [comment]
Mais même si je n'affiche pas le samedi le problème se produit. Mais oui, j'ai PRE011.
![image](https://github.com/ApplETS/Notre-Dame/assets/83369199/85199853-a0bc-4adc-a74e-5b25b016abd6)

**Comment by LouisPhilippeHeon** [comment]
Dans ma branche ou je travaille sur le layout horizontal, le problème est réglé. Éventuellement ce sera prêt à mettre en PR.
