### ISSUE TITLE
Les marges entre les tuiles de la section "ETS" sont trop grandes lorsque le téléphone est en mode paysage.

### ISSUE THREAD

**Issue by LouisPhilippeHeon** [ApplETS/Notre-Dame#880]
![3DBAEEC7-F129-44BC-B3C7-7373570513FA](https://github.com/ApplETS/Notre-Dame/assets/83369199/8a084d4b-42d7-43ca-8ca8-2bf182532349)
Aussi, on pourrait profiter de l'écran plus large pour afficher plus de tuiles sur la même ligne.

**Comment by MysticFragilist** [comment]
Hmmm moi c'est bizarre je n'ai pas l'issue sur mon téléphone:

![image](https://github.com/ApplETS/Notre-Dame/assets/25663435/6201a4ae-19cb-4f57-b469-3937f7a31b2a)


@ApplETS/general quelqu'un est capable de reproduire?

**Comment by LouisPhilippeHeon** [comment]
C'est de plus en plus bizarre comme problème, parce que en mode portrait sur mon téléphone tout s'affiche correctement, mais sur la version Mac (qui est basically la version iPad), le problème est visible, peut importe l'orientation.
<img width="1470" alt="Capture d’écran, le 2023-10-27 à 21 42 18" src="https://github.com/ApplETS/Notre-Dame/assets/83369199/85132a11-719b-43ab-be6d-f417887a2093">
<img width="728" alt="Capture d’écran, le 2023-10-27 à 21 42 43" src="https://github.com/ApplETS/Notre-Dame/assets/83369199/c21e845a-a51f-480a-925a-b51e3029c64a">

**Comment by MysticFragilist** [comment]
Hmmm c'est pt un problème uniquement sur iOS dans ce cas! Je pense que ça pourrait corréler avec le changement au niveau de rendre les quicklinks reorderable. 
@LouisPhilippeHeon tu es sur la nouvelle version iOS right? 4.28.2? Tu peux aller voir dans "Plus" > "Licence open-source"

@JonathanDuvalV t'en pense quoi?

**Comment by LouisPhilippeHeon** [comment]
C'est bien la dernière version, la 2.28.2. J'ai aussi rallumé mon vieux iPad et je peux confirmer que ça s'affiche exactement comme sur le Mac, comme je m'y attendais. Ce que je trouve spécial c'est que le problème est tout le temps présent sauf sur un iPhone à la verticale. 🤔
