### ISSUE TITLE
Padding between the first card and the top navigation too large

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#881]
**Describe the bug**
The padding between the first card and the top navigation too large.

**To Reproduce**
1. Go to any grade details page.
2. See the padding between the card and the top drawer.

**Expected behavior**
It would be really neat to have the same padding as between the global grade card and the median card:

**Screenshots**
<img width="340" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/25663435/a69f1c3b-09c7-4ebe-85a7-04627396804f">

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any

**Additional context**
N/A

**Comment by XavierPaquet-Rapold** [comment]
Fixed with #946
