### ISSUE TITLE
La réorganisation des sections de la page d'accueil ne se comporte pas de manière intuitive.

### ISSUE THREAD

**Issue by LouisPhilippeHeon** [ApplETS/Notre-Dame#882]
Version 4.28.3
iOS 17.0.3, iPhone 13 Pro

https://github.com/ApplETS/Notre-Dame/assets/83369199/8659fa91-eaae-4bb7-bb86-25c5e4d30b4a

**Comment by MysticFragilist** [comment]
Probablement un bogue de régression sur la nouvelle version je suis capable de reproduire sur un iphone 15.

**Comment by HugoMigner** [comment]
> Probablement un bogue de régression sur la nouvelle version je suis capable de reproduire sur un iphone 15.

Je pensais que c'était un bug en lien avec la broadcast card, mais j'ai pas ce bug sur Android, donc oui très probablement dû à la régression!
