### ISSUE TITLE
Il me reste un examen jeudi, sur l'autre version j'arrive à la voir mais pas sur la beta
PS Dashboard est maintenant écrit au complet lorsqu'il est sélectionné depuis la dernière mise à jour! 

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#89]
**What happened:**
```
Il me reste un examen jeudi, sur l'autre version j'arrive à la voir mais pas sur la beta
PS Dashboard est maintenant écrit au complet lorsqu'il est sélectionné depuis la dernière mise à jour! 
```

**Version:** 3.0.0-beta (30747)

**Operating system:** Android 7.0

**Model:** samsung SM-G903W

**Memory:** 82% (1.48 GB used out of 1.82 GB)

**Capacity:** 84% (9.28 GB used out of 11 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/11/awesome_logs) 

**Attachments:** 

![screenshot_1555362646512.png](http://buglife.s3.amazonaws.com/report_attachments/bd42dace335d304444f4c6dfda32e7ee153f85a1/original/screenshot_1555362646512.png?1555362862)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/11

Reported via Buglife

**Comment by Sonphil** [comment]
Should be fixed in #174
