### ISSUE TITLE
Add teacher name and email adress when you click on a course grades summary

### ISSUE THREAD

**Issue by AmineMihoubi** [ApplETS/Notre-Dame#895]
**Description**
As a student, I would like to see the teacher name and maybe his email address too when I click on a course grades summary

**Describe the solution you'd like**
Add the information somewhere there maybe ?
![Screenshot 2023-11-17 105452](https://github.com/ApplETS/Notre-Dame/assets/64211553/5ddea4f2-ee2d-42a5-8c11-528f1bf3d150)

Or maybe like that
![Screenshot 2023-11-17 110325](https://github.com/ApplETS/Notre-Dame/assets/64211553/e2adcc0c-c904-46b3-b640-41b7496ae852)

**Comment by AmineMihoubi** [comment]
Le code est déja la, mais pour chaque cours le nom de l'enseignant est null. L'api n'envoie l'info ?

**Comment by EffBureau** [comment]
@AmineMihoubi As-tu essayé avec un autre cours que PRE011?

**Comment by XavierPaquet-Rapold** [comment]
Voici un exemple de ce qu'on reçoit lorsqu'on appelle listeHoraireEtProf:

```xml
<listeHoraireEtProfResponse xmlns="http://etsmtl.ca/">
    <listeHoraireEtProfResult>
        <erreur />
        <listeActivites>
            <HoraireActivite>
                <sigle>LOG210</sigle>
                <groupe>01</groupe>
                <jour>1</jour>
                <journee>Lundi</journee>
                <codeActivite>C</codeActivite>
                <nomActivite>Activité de cours</nomActivite>
                <activitePrincipale>Oui</activitePrincipale>
                <heureDebut>08:30</heureDebut>
                <heureFin>12:00</heureFin>
                <local>A-1302</local>
                <titreCours>Analyse et conception de logiciels</titreCours>
            </HoraireActivite>
        </listeActivites>
        <listeEnseignants>
            <Enseignant>
                <nom>Nom</nom>
                <prenom>Prenom</prenom>
                <courriel>Courriel</courriel>
                <localBureau>A-0000</localBureau>
                <telephone>Téléphone avec poste</telephone>
                <enseignantPrincipal>Oui</enseignantPrincipal>
            </Enseignant>
        </listeEnseignants>
    </listeHoraireEtProfResult>
</listeHoraireEtProfResponse>
```
J'ai modifié les informations de l'enseigant.

**Comment by AmineMihoubi** [comment]
Story bloquée en attendant d'avoir une nouvelle route qui retourne les enseigants avec les cours

**Comment by AmineMihoubi** [comment]
L'api qui donne les noms des enseignants refonctionne
