### ISSUE TITLE
Text in the grades tiles are not displayed well when the text size is not the default one

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#91]
**Describe the bug**
The tiles do not wrap the text correctly when the text size set in the phone settings is bigger than the default one. 
The other pages of the app seems fine.

**To Reproduce**
Steps to reproduce the behavior on an iPhone:
1. Go to settings
2. Go to Display & Brightness
3. Go to Text Size
4. Set the Text Size to the fourth, fifth or sixth size
5. Launch the ÉTSMobile app
4. Go to 'Student'

**Screenshots**
<img src="https://user-images.githubusercontent.com/37625944/113463681-49d68c00-93f5-11eb-968f-03254e4e6a42.png"
    width=300px />

**Smartphone**
 - Device: iPhone 11

**Comment by apomalyn** [comment]
Good catch! :D It's because the grades button has a default width! I will fix that ASAP
