### ISSUE TITLE
Android 13: themed icons support

### ISSUE THREAD

**Issue by edgarogh** [ApplETS/Notre-Dame#916]
### Context

Android 13 (API level 33) supports "themed icons" on the app launcher, where users can customize the colors of a monochrome icon. This is an extension of Android's "adaptive icons". ETS Mobile doesn't support this, breaking the coherence of the app launcher UI:

![Screenshot_20231228-183748.png](https://github.com/ApplETS/Notre-Dame/assets/46636609/4db8f165-6b93-438a-aad4-6f8a95e758a3)

### Solution

Fixing this should be as simple as adding a `<monochrome>` tag in [this file](https://github.com/ApplETS/Notre-Dame/blob/master/android%2Fapp%2Fsrc%2Fmain%2Fres%2Fmipmap-anydpi-v26%2Flauncher_icon.xml) (I think), pointing to a monochrome version of the app logo. All relevant docs, including icon design guidelines can be found [on the official Android docs](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive).

---

If you approve this suggestion, I'll gladly fix it in a PR myself. (FYI I'm not in the club)

**Comment by MysticFragilist** [comment]
I approve this suggestion! You can make a PR! The only thing thought, is that make sure the default icon color is still the ÉTS red color :)

**Comment by edgarogh** [comment]
> make sure the default icon color is still the ÉTS red color

Just to be clear, the "themed icons" are only displayed if the user has the corresponding setting enabled on their app launcher. By default – and on launchers that don't support this themed icons feature (incl. older devices) – the current red icon will be used as a default/fallback. This is really just an additive enhancement that shouldn't cause any unwanted regression.

Anyway, I'll change that as soon as I have access to my laptop 😀
