### ISSUE TITLE
[DONE] Rubik was changed to horairÉTS

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#932]
**Describe the issue** 
```Sur l'application Android, la section rubik mène sur un lien vide```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-921178269.png?raw=true)

**Device Infos** 
- **Device:** SM-G990W 
- **Version:** 4.21.5 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1679695472 
- **Platform operating system:** android 
- **Platform operating system version:** UP1A.231005.007.G990WVLSAFXA1 
- **Email:** edouardlarouche04@gmail.com

**Comment by MysticFragilist** [comment]
Il reste à lui répondre par courriel

**Comment by MysticFragilist** [comment]
Répondu!
