### ISSUE TITLE
Grade for multi-professor class becomes 0% after evaluating one professor

### ISSUE THREAD

**Issue by DylanApardian** [ApplETS/Notre-Dame#941]
**Describe the bug**

During the course evaluation period, Signets requires the student to evaluate the professors of their classes in order to see their grades.

When the student hasn't completed the evaluation of a class, ETSMobile displays the grade as `N/A` until the student has evaluated the professor.

However, classes with multiple professors require the student to evaluate all the professors before having access to their grades.
Currently, if the student evaluates 1 professor out of 2, their grade on ETSMobile goes from `N/A` to `0%`

**To Reproduce**

1. Find a course with multiple professors to evaluate during the evaluation period
2. Verify that your grade is `N/A` when no professors have been evaluated during the evaluation period
3. Evaluate 1 professor of the course with multiple professors
4. Verify that your grade has become `0%`

**Expected behavior**

The grade should remain `N/A` until all the professors of that course have been evaluated.

**Screenshots**

![image](https://github.com/ApplETS/Notre-Dame/assets/155918717/42282bd0-f641-4d23-ab7f-28a7c402e697)
![image](https://github.com/ApplETS/Notre-Dame/assets/155918717/682b07ce-32c1-42f1-b38e-0c750f5f8428)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14
 - Browser: Chrome v122
 - Version: 4.33.2 (ETSMobile)

**Comment by XavierPaquet-Rapold** [comment]
To add more informations, the fix will be in the CourseRepository getReviewForCourseClass which saves only one review for each course.
![image](https://github.com/ApplETS/Notre-Dame/assets/80051842/8c168fe5-cc38-4876-aa0d-e497b5df9049)
