### ISSUE TITLE
Migrate to gradle declarative plugins block

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#945]
**Describe the bug**
With the new flutter 3.19.3 we use, a warning pops up when building on android. It says that gradle needs to be migrated to a new template defined in the following link: https://flutter.dev/go/flutter-gradle-plugin-apply. This issue would be to migrate according to the link the gradle files to prevent being block on a future flutter version.

Also, Android NDK version warning should be mitigated.

**To Reproduce**
1. Build solution on android
2. See the warning

**Expected behavior**
The warning should not appear anymore and gradle should be ported to use declarative plugins block.

**Screenshots**
<img width="1769" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/25663435/62acadae-7df1-4083-b32a-1b3428ad8ef7">
<img width="628" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/25663435/7f01bcb9-63b0-417f-a2b1-47fdcb13f9a8">

**Smartphone (please complete the following information):**
Android only

**Additional context**
N/A

**Comment by XavierPaquet-Rapold** [comment]
Done with #1093
