### ISSUE TITLE
The balance doesn't update

### ISSUE THREAD

**Issue by apomalyn** [ApplETS/Notre-Dame#97]
**Describe the bug**
I paid a part of my balance and the profile on the app doesn't display the new balance (but beta does). It's like the refresh doesn't happen. 

**To Reproduce**
1. Go to profile (first time to create the cache)
2. Kill the application
3. Pay a part of your balance then wait 2-3 days
4. Reopen the application and go to the profile section.

**Expected behavior**
The profile should update itself each time the profile is loaded.

**Comment by MysticFragilist** [comment]
I think we fixed it but I'll have to test it and tell you in 2-3 days hahaha

**Comment by MysticFragilist** [comment]
Actually the fix worked, I had an old balance from two weeks ago and when I reloaded the app with the fix it showed the right balance. I'll make a PR for that!

**Comment by apomalyn** [comment]
Ahah ok, keep me updated :smile:

**Comment by apomalyn** [comment]
@MysticFragilist soooo is that fixed? :smile:

**Comment by MysticFragilist** [comment]
hmm for some reason it doesn't work, BUT it seems like it could (i know how it sounds hahaha), maybe it's because I switch across two branches when developing. The fix I did was pretty easy I only removed the `fromCacheOnly` attribute in the `futureToRun` function. 
```dart
@override
  Future<List<Program>> futureToRun() => _userRepository
          .getInfo()
          .then((value) => _userRepository.getPrograms(fromCacheOnly: true))
          .then((value) {
        setBusyForObject(isLoadingEvents, true);
        _userRepository
            .getInfo()
            // ignore: return_type_invalid_for_catch_error
            .catchError(onError)
            // ignore: return_type_invalid_for_catch_error
            .then((value) => _userRepository.getPrograms().catchError(onError))
            .whenComplete(() => setBusyForObject(isLoadingEvents, false));
        return value;
      });
```

By looking at the code inside getInfo, it seems like it's doing the right thing by fetching from API directly. I'll need to investigate more.

**Comment by apomalyn** [comment]
This bug is still happening but I think I found one of the problems: when we refresh (pull-for-refresh) we only reload the programs of the student, not the info linked to him [see here](https://github.com/ApplETS/Notre-Dame/blob/master/lib/core/viewmodels/profile_viewmodel.dart#L84). 
I will look into it when moving the package id to the new one.
